### ISSUE TITLE
Changing tabs should switch all code samples on the page

### ISSUE THREAD

**Issue by mDuo13** [XRPLF/xrpl-dev-portal#1007]
Many pages have multiple examples with code samples in multiple programming languages or styles (JSON-RPC / WebSocket, soon ripple-lib / xrpl-py, etc.). It would be handy if changing tabs on one code sample automatically changed tabs on all code samples to match.

Of course, this will only work if the other examples on the same page have the same tabs, but that's probably good enough for most cases.

Relevant JS file: [multicodetab.js](https://github.com/ripple/xrpl-dev-portal/blob/master/assets/js/multicodetab.js).

Depending on how the changes work, this could also be something to port upstream [to Dactyl's version](https://github.com/ripple/dactyl/blob/master/examples/template_assets/multicode_tabs.js). (Changes to Dactyl's [multicode tabs](https://github.com/ripple/dactyl/blob/master/dactyl/filter_multicode_tabs.py) filter might also be necessary, though hopefully they can be backwards compatible with the old JavaScript for anyone who's still using that one.)

**Comment by q411** [comment]
https://github.com/ripple/xrpl-dev-portal/labels/web%20dev

**Comment by q411** [comment]
https://github.com/ripple/dactyl/blob/master/examples/templatehttps://github.com/ripple/dactyl/blob/master/dactyl/filter_multicode_tabs.py_assets/multicode_tabs.js

**Comment by q411** [comment]
https://github.com/ripple/xrpl-dev-portal/blob/master/assets/js/multicodetab.js

**Comment by mDuo13** [comment]
Fixed by #1098
