### ISSUE TITLE
Create "Advanced Transaction Usage" tutorial group

### ISSUE THREAD

**Issue by mDuo13** [XRPLF/xrpl-dev-portal#1008]
Move existing tutorials into this area:

- Reliable Transaction Submission
- Monitor Incoming Payments with WebSocket
- Send a Multi-Signed Transaction
- Use Tickets

New tutorial ideas that would fit into this category:

- Batch transaction sending (tracking your sequence number, what to do if you're queued, why & how to [cancel a transaction rather than re-number all the transactions after it](https://xrpl.org/about-canceling-a-transaction.html))
- Refunding Unwanted Payments (base on [Bouncing Payments](https://xrpl.org/become-an-xrp-ledger-gateway.html#bouncing-payments) in the gateway guide)

**Comment by q411** [comment]
https://github.com/ripple/xrpl-dev-portal/labels/nehttps://github.com/ripple/xrpl-dev-portal/labels/organizationw%20topic

**Comment by q411** [comment]
https://xrpl.org/about-canceling-a-transaction.htmlhttps://xrpl.org/become-an-xrp-ledger-gateway.html#bouncing-payments

**Comment by nbougalis** [comment]
Hi @q411! I notice that you've posting links with no further context or explanation on several topics. Could you please explain, in words, the rationale behind posting the links? What is it you're trying to indicate or achieve?

**Comment by q411** [comment]
Lol I am sorry hope you are having a great day! I’m just tryin to fix some
issues and some links I’m not meaning to post hahaha😁

**Comment by nbougalis** [comment]
Thank you, I'm having a great day! I hope you are as well. :vulcan_salute: 

The posts just caught the attention of a co-worker who was receiving several e-mail notifications about them, so we just wanted to follow up.

We very much welcome contributions, so please feel free to continue to try and resolve issues and submit pull requests.

**Comment by mDuo13** [comment]
Closing this since the main reorganization work is covered in the updated information architecture stuff, and the following issues cover the proposed new tutorials:

- #1025
- #1647
