### ISSUE TITLE
Investigate & document "freebie" trust lines

### ISSUE THREAD

**Issue by mDuo13** [XRPLF/xrpl-dev-portal#1034]
Supposedly, it is possible for a user to have up to 2 trust lines without needing to pay the reserve.

https://github.com/ripple/rippled/blob/866425738194a4dda2d142dfc7e73cdea71d526d/src/ripple/app/tx/impl/SetTrust.cpp#L153-L167

Investigate and update the [Reserves](https://xrpl.org/reserves.html) page with the exceptions.

**Comment by DennisDawson** [comment]
This has been documented here: https://xrpl.org/docs/concepts/tokens/fungible-tokens/#free-trust-lines
