### ISSUE TITLE
Diagram(s) on the amendment process

### ISSUE THREAD

**Issue by mDuo13** [XRPLF/xrpl-dev-portal#1035]
A flowchart or something to represent the [amendment process](https://xrpl.org/amendments.html#amendment-process) might aid understanding. One or more diagrams could try to encompass:

- the "happy path" from an amendment being open for voting, to gaining majority, to becoming enabled
- the "rocky path" path where an amendment gains/loses majority several times before finally getting enabled
- the "unhappy path" where an amendment eventually gets removed from the source without ever being enabled
- how old amendments can be "unconditionalized" which removes support for legacy ledger playback
- how old servers from before the amendment become amendment blocked if an amendment they don't support gets enabled

**Comment by mDuo13** [comment]
There's a diagram in the legacy [Feature adoption Ripple wiki page](https://web.archive.org/web/20150422101235/https://wiki.ripple.com/Understanding:_Feature_adoption) that is not very good but might serve as inspiration for part of this (note, that page was speculative and things don't actually work as described there)

**Comment by mDuo13** [comment]
#1667 should fix this issue

**Comment by oeggert** [comment]
Will work on an updated diagram after #1667 process is finalized.
