### ISSUE TITLE
Any way to resolve an issues with ledger reserve fees

### ISSUE THREAD

**Issue by nincompoop88** [XRPLF/xrpl-dev-portal#1076]
Im a user needing advice. Would love to help beta test and contribute. 

My question is what to do when we accidentally open a second ripple ledger account. For example I accidentally sent 33 xrp to trustwallet while I was attempting to exchange it to some xlm to make a trade as i thought I could do that since coin base was not exchanging it. I hadnt yet seen the notice on the sec lawsuit halting all exchanges and conversions of xrp beforehand.  So I inadvertently opened a second xrp ledger, I already have one on the exodus ledger/wallet and was trying to avoid another 20 xrp reserve. I missed. 

So is there anyway to get 15 of the xrp reserve back out of my trustwallet since I did not mean to start another xrp ledger since I already have one on exodus? 

Would greatly appreciate assistance 

Sincerely
A nincompoop n00b

**Comment by ximinez** [comment]
If both of the accounts are on ledger, and not exchange accounts, I think what you want is to delete one of your accounts. The instructions for that are at https://xrpl.org/accountdelete.html#accountdelete

If the XRP is on an exchange, you'll have to contact the exchange for support.

I'm going to close this ticket, but please feel free to reopen it if I haven't answered your question, or if you have further questions.
