### ISSUE TITLE
Link to a private YouTube video so users cannot see the video

### ISSUE THREAD

**Issue by timothyTheCoder** [XRPLF/xrpl-dev-portal#1082]
See https://xrpl.org/consensus.html and at the bottom there is a link to a video about consensus named **Ripple consensus video** bit it’s [rivale so users cannot see it.

**Comment by boncryp** [comment]
Hi
Is it possible to watch the consensus video as it asks for permission.

Thanks for your time

Regards

Boncryp

**Comment by timothyTheCoder** [comment]
When you click on the link, you are taken to YouTube and this is the screen I get on my iPhone. So I assume if I can’t watch the video, others can’t either as it’s a private video.

![7FD9D6CD-0666-447B-AF2C-16D331780B2F](https://user-images.githubusercontent.com/9657088/119136039-73985080-ba3f-11eb-8344-76ae4d000d20.jpeg)

**Comment by mDuo13** [comment]
Fixed by #1317
