### ISSUE TITLE
Code example for issuing an asset

### ISSUE THREAD

**Issue by will-yjn** [XRPLF/xrpl-dev-portal#1101]
https://developers.ripple.com/issued-currencies.html

This link has word explanations but no code example. I tried to follow the instructions to issue an asset to no avail. Below are my code:
`
    // Submit a transaction to set the DefaultRipple flag on the account
    // https://xrpl.org/accountset.html
    const txnObj = {
        "TransactionType": "AccountSet",
        "Account": from,
        "Fee": "15",
        "Flags": 0,
        "SetFlag": 8,
        "Sequence": sequence,
    };
    const setFlagBool = await signAndSend(txnObj);
    
    // Choose a three-character code for your asset

    // Set up a trust link between two accounts
    // https://xrpl.org/trustset.html
    const trustTxnObj = {
        "TransactionType": "TrustSet",
        "Account": to,
        "Fee": "12",
        "Flags": 262144,
        "LimitAmount": {
          "currency": "TST",
          "issuer": from,
          "value": "10000"
        },
        "Sequence": sequence
    };
    const setTrustLinkBool = await signAndSend(trustTxnObj);

    // To issue your asset to people just use a Payment transaction
    const assetTxnObj = {
        TransactionType: 'Payment',
        Account: from,
        Destination: to,
        DestinationTag: tag ? Number(tag) : 0,
        Amount: {
            "currency" : "TST",
            "value" : "1",
            "issuer" : from
        },
        Fee: fee,
        Sequence: sequence,
        SigningPubKey: publicKey,
    };
    const issueAssetBool = await signAndSend(assetTxnObj);
`
The first two transactions returned "RippledError: invalidTransaction". The third just hang. What is the correct way?

**Comment by mDuo13** [comment]
The full process is described in the [Issue a Fungible Token](https://xrpl.org/issue-a-fungible-token.html) tutorial with fully functional [code samples](https://github.com/XRPLF/xrpl-dev-portal/tree/master/content/_code-samples/issue-a-token/js). I don't see anything obviously wrong with your example code, so maybe the error is in the supporting code somewhere. In any case, take a look at the provided sample code and see if that answers your question.
