### ISSUE TITLE
Some images are hard to read

### ISSUE THREAD

**Issue by mvadari** [XRPLF/xrpl-dev-portal#1135]
The image at https://xrpl.org/ledger-object-ids.html is basically impossible to read on the black background. I had to open the image in a new tab, where it opened against a white background, to be able to understand it.

I've seen this issue on one or two other pages as well, but I can't recall where exactly.

**Comment by mvadari** [comment]
Another example: https://xrpl.org/paths.html

**Comment by mDuo13** [comment]
This was a regression caused by a CSS change. Fixed now.
