### ISSUE TITLE
Add `sign` to list of Admin rippled methods

### ISSUE THREAD

**Issue by intelliot** [XRPLF/xrpl-dev-portal#1137]
Since [`sign`](https://xrpl.org/sign.html) is now admin-only by default, perhaps it should be added to the list here: https://xrpl.org/admin-rippled-methods.html

**Comment by mDuo13** [comment]
Probably both `sign` and `sign_for` should be moved out of the public methods section? Maybe they can be linked in both places since they _can_ be public methods if enabled, but since they're no longer public by default they should be in the admin category now.

**Comment by amarantha-k** [comment]
PR #1209 that fixes this issue has been merged.
