### ISSUE TITLE
wallet_propose example disappears when switching request format

### ISSUE THREAD

**Issue by JST5000** [XRPLF/xrpl-dev-portal#1141]
In the wallet_propose documentation (https://xrpl.org/wallet_propose.html#code-0-1) there is a commandline example of how to call the function. If you click any of the 4 format types (Websocket, JSON-RPC with and without key type) the example disappears. Refreshing the page brings back the original example. The format for the four formats is also different than the same buttons on a similar function (Ex. https://xrpl.org/validation_create.html), so maybe this is caused by a legacy component being used on wallet_propose's documentation page?

Before:
<img width="1440" alt="Before" src="https://user-images.githubusercontent.com/19694186/128764261-fe55c54a-beb5-4f64-ad26-fb1817bf1be7.png">

After: (There's no longer any example, and the text formats oddly)
<img width="1440" alt="After" src="https://user-images.githubusercontent.com/19694186/128764453-bd9d9783-37b4-4590-a3b2-596896380c46.png">

Note: Clicking on any type other than "Commandline" does not bring up any examples, and clicking "Commandline" DOES bring up a different example than the one initially shown on the page:
<img width="1440" alt="Clicking Commandline" src="https://user-images.githubusercontent.com/19694186/128765142-926da400-35f7-450d-8c99-f02ee41e8a54.png">

For reference: I am using Chrome Version 92.0.4515.131 (Official Build) (x86_64)

**Comment by mvadari** [comment]
I'm running into this issue on a number of other pages as well (such as https://xrpl.org/ledger_data.html)

**Comment by mDuo13** [comment]
Looks like a bug introduced by #1098. @jakeatdocforce, can you take a look at this?
