### ISSUE TITLE
Dev Tools is under Docs on the home page

### ISSUE THREAD

**Issue by cjcobb23** [XRPLF/xrpl-dev-portal#1147]
To get to Dev Tools, users first have to click on Docs. I don't think the dev tools count as documentation. I always forget where the dev tools link is because it's not documentation. The dev tools are very useful as well; I think it would be appropriate for dev tools to have it's own button right next to docs, on the home page at the top level.

**Comment by mDuo13** [comment]
This has been resolved. Dev Tools are now under Resources.
