### ISSUE TITLE
Lost XRP

### ISSUE THREAD

**Issue by StevieSimple** [XRPLF/xrpl-dev-portal#1153]
Can u please help me get my 120 XRP back? I mistakenly sent without DT! My Pionex address 
rw5z4hdpz6qUyjGXSZwfyAVZHK7r3hsbPz
Find following the ledger and transaction entry
Block 64780078
Entry 36
Went to following address
rJnUXy7x3RW58Kien2eFtZEY2Pa3HBvpQ2

Copy of raw transaction 
"root":{
20 items

"Amount":{
2 items
"value":
int120263200
"currency":
string"XRP"
}

"meta":{
4 items

"delivered_amount":{
2 items
"value":
int120263200
"currency":
string"XRP"
}

"AffectedNodes":[
...
]
2 items
"TransactionIndex":
int36
"TransactionResult":
string"tesSUCCESS"
}

"Paths":[]
0 items
"Account":
string"rw5z4hdpz6qUyjGXSZwfyAVZHK7r3hsbPz"
"Destination":
string"rJnUXy7x3RW58Kien2eFtZEY2Pa3HBvpQ2"
"DestinationTag":
int0
"Fee":
int10000
"Flags":
float2147483648
"LastLedgerSequence":
float4294967290
"Sequence":
int13062
"SigningPubKey":
string"03B3CC1D4950F538BCDE364DB01241163A0D7D892FC35A13AB92539E10CD0251..."
"TransactionType":
string"Payment"
"TxnSignature":
string"304502210096B58575D284DF4E2EC356DA4C28F631FECB603A383E2CC03A0DB2..."
"hash":
string"7A1C6117A9CA87A348B0ABFD29D3BEDA623BE3DA4C3380ECCBC83F94497A5591"
"ledger_index":
int64780078
"date":
string"2021-07-07T09:11:22.000Z"

"Memos":[]
0 items
"AccountName":
NULL
"DestinationName":
NULL
"AmendmentName":
NULL
}

**Comment by ximinez** [comment]
You will need to contact the recipient to get your funds returned or properly credited. There is absolutely nothing anybody else can do to get your funds back.

**Comment by StevieSimple** [comment]
Hi thanks for ur response. My problem is I don't know who's the recipients? I think it's Hubi exchange or Lobstr wallet a Stella exchange?
I ask Pionex where the transaction originated at but no response? Any suggestions would be greatly appreciated n possible small reward?
Unity through Prosperity 
Peace Out LFBF TYHP

**Comment by StevieSimple** [comment]
Not sure of recipient Hubi exchange or Stella Lobstr wallet exchange? Does anyone know? Thanks for the help?
Unity through Prosperity!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by cjcobb23** [comment]
> Went to following address
> rJnUXy7x3RW58Kien2eFtZEY2Pa3HBvpQ2

You need to contact the owner of this address. They have your XRP.

**Comment by timothyTheCoder** [comment]
Maybe this can help you find out more: https://bithomp.com/explorer/rJnUXy7x3RW58Kien2eFtZEY2Pa3HBvpQ2
You can hopefully check who activated it and go from there.

**Comment by mDuo13** [comment]
Closing this issue as it doesn't relate to documentation or xrpl.org but I hope you're able to get your XRP back.
