### ISSUE TITLE
rippled version chart on network explorer

### ISSUE THREAD

**Issue by jscottbranson** [XRPLF/xrpl-dev-portal#1161]
I think it would be useful (for things like amendment voting decisions) to have a chart showing what proportion of the network is running a given version of rippled on the livenet.xrpl.org/network page.

Something similar to the chart in the top right of this page: https://xrpcharts.ripple.com/#/topology

While the chart on the ripple.com page appears accurate, I think there are still multiple reasons (convenience, ensuring data accuracy, independent data, etc.) that having the chart on xrpl.org would be beneficial.

Cheers!

**Comment by mDuo13** [comment]
Closing this one in favor of the task in the explorer repo
