### ISSUE TITLE
Copy-paste button for bash commands includes the `$`

### ISSUE THREAD

**Issue by mvadari** [XRPLF/xrpl-dev-portal#1196]
I'm trying to follow the instructions at https://xrpl.org/build-run-rippled-macos.html to install rippled, and the copy-paste buttons for the command line commands all include the `$`, which means that when I copy-paste the commands I have to go back and delete the `$` at the beginning.

**Comment by mDuo13** [comment]
[The Markdown style guide I often use suggests not using $ unless the code block also includes result outputs](https://cirosantilli.com/markdown-style-guide/#dollar-signs-in-shell-code), so I think changing to follow that guideline will resolve this problem. (You probably won't want to copy a code block that includes an example response, after all.)

**Comment by mDuo13** [comment]
Fixed by #1237.
