### ISSUE TITLE
Livenet network page shows restricted IP Addresses

### ISSUE THREAD

**Issue by jscottbranson** [XRPLF/xrpl-dev-portal#1201]
Occasionally a 10./8 or other private IPv4 address shows up on https://livenet.xrpl.org/network

It seems like it would be beneficial to have the livenet tool censor bogons, if it isn't too much work.

I'm going to also file a rippled issue suggesting a config option so a node can have an 'advertised address', but it seems like it makes sense to try to address this issue from both ends. I'm not 100% why this behavior occurs, but I suspect it happens when a peer on the same LAN as a given server reports information on that server to livenet.

Thanks

**Comment by mDuo13** [comment]
Issues with livenet.xrpl.org should go to the https://github.com/ripple/explorer/ repo.

**Comment by jscottbranson** [comment]
Thanks, @mDuo13
