### ISSUE TITLE
Peer network crawler Github link should be updated

### ISSUE THREAD

**Issue by mvadari** [XRPLF/xrpl-dev-portal#1211]
At the bottom of [this page](https://xrpl.org/peer-crawler.html), there is a link to https://github.com/ripple/rippled-network-crawler. This should probably be updated to the [VHS Github repo](https://github.com/ripple/validator-history-service), since that is now open-source and is what the Explorer uses.

**Comment by mDuo13** [comment]
Fixed by #1229.
