### ISSUE TITLE
More debugging info for installing rippled

### ISSUE THREAD

**Issue by mvadari** [XRPLF/xrpl-dev-portal#1212]
I was installing rippled on my Mac and using [these instructions](https://xrpl.org/build-run-rippled-macos.html). I ran into an issue, and gave up. My only way of debugging was asking someone else at Ripple to help me out. (I figured it out a few months later that I needed to reinstall `openssl`). 

There should be more information for people installing `rippled` for what possible issues are and how to resolve them.

**Comment by mDuo13** [comment]
While I don't disagree with the sentiment, it's hard to take action on a general "more troubleshooting/debugging info" request. I'm going to close this task, but we can still add specific error cases/messages and solutions as they come up (in separate tickets).

**Comment by mvadari** [comment]
This issue was opened over a year ago and rippled now uses conan, so I don't remember what the specific issue I had was, and it's also probably no longer relevant.
