### ISSUE TITLE
Use card design for generic category landing page

### ISSUE THREAD

**Issue by mDuo13** [XRPLF/xrpl-dev-portal#1217]
Redesign the `pagetype-category.html.jinja` template to use cards rather than bullet points, for consistency with the visual language of the other pages. The cards don't need unique card-bottom graphics. The left sidebar should still be present on these pages, but they don't need a right sidebar.

We may do a more thorough revision of the pages later to improve the navigation experience, but for now we're just giving them a slight facelift.

**Comment by amarantha-k** [comment]
Repurpose this ticket to design new landing pages for use cases.

**Comment by amarantha-k** [comment]
Related Issue #2093

**Comment by amarantha-k** [comment]
Closing this issue as #2093 will address this issue.
