### ISSUE TITLE
Wrong URLs in Historical database API Tool

### ISSUE THREAD

**Issue by matejr** [XRPLF/xrpl-dev-portal#122]
Pages

https://ripple.com/build/historical-database-api-tool/#get-account-transaction-history
https://ripple.com/build/historical-database-api-tool/#get-transaction-by-account-and-sequence
https://ripple.com/build/historical-database-api-tool/#get-transaction
https://ripple.com/build/historical-database-api-tool/#get-ledger

contain text: "https://api.ripple.com" instead of "https://history.ripple.com".

HTTP GET requests like:

https://api.ripple.com/v1/ledgers/3170DA37CE2B7F045F889594CBC323D88686D2E90E8FFD2BBCD9BAD12E416DB5?transactions=true&binary=false&expand=true

don't work.

**Comment by mDuo13** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

Good catch. Fixed.
- --Rome R.
  Documentation Engineer

On 03/23/2015 06:28 AM, Matej Rizman wrote:

> Pages
> 
> https://ripple.com/build/historical-database-api-tool/#get-account-transaction-history
> 
> https://ripple.com/build/historical-database-api-tool/#get-transaction-by-account-and-sequence
> https://ripple.com/build/historical-database-api-tool/#get-transaction
> https://ripple.com/build/historical-database-api-tool/#get-ledger
> 
> contain text: "https://api.ripple.com" instead of
> "https://history.ripple.com".
> 
> HTTP GET requests like:
> 
> https://api.ripple.com/v1/ledgers/3170DA37CE2B7F045F889594CBC323D88686D2E90E8FFD2BBCD9BAD12E416DB5?transactions=true&binary=false&expand=true
> 
> don't work.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ripple/ripple-dev-portal/issues/122.

-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2

iQEcBAEBCAAGBQJVEEVpAAoJEH/Cu7yklc5nfj8H/1jXMoa6tibuBdnZxwYGkyCP
Hde3ZJKyb2I0ORYfnu9Eum/jqnCjop0rBpv7OTpNuS5FOSGusjAZK47Cxm+aeo6D
UR00aOV8DF8pwFOYvxCxjesdYOY24Xy7HgP9wIXjpXR3WPtoI9bf4UStEDhmsek6
ikZkV/9tjgCmFDLiqwB1OsgM2eK+7tszS8FA9QB2eberpntAotDHu48GgavFF+eq
mk2QAScpb9+91rnUbkpmfJe5A1gbBJrLydFv1GfQ2pO9WU+L35qNEigM6gTPAyBo
oKkAT9W5oHO2kzh0FVzLWEcKJzPel9TcXJXymfMdaLkJ0LmmicqUglA4uKBA0SQ=
=8yo0
-----END PGP SIGNATURE-----
