### ISSUE TITLE
Update Escrow tutorials

### ISSUE THREAD

**Issue by mDuo13** [XRPLF/xrpl-dev-portal#1221]
The [Escrow tutorials](https://xrpl.org/use-escrows.html) have examples in WebSocket, and in JS using ripple-lib 1.x, but they could really stand to be updated. Currently the JS example code is not even used directly in the pages.

- Update the example JavaScript to xrpl.js 2.x
- Add bits from the JavaScript examples into the tutorial pages, probably using the `{{ include_code() }}` macro.
- (Optional) Provide examples in other languages like Python. (This may be difficult depending on the availability of crypto-conditions libraries)
- (Optional) Make the tutorials interactive.

**Comment by oeggert** [comment]
@DennisDawson Adding you to this issue since you're already working on the escrow tutorials.

**Comment by amarantha-k** [comment]
This looks to have been done: https://github.com/XRPLF/xrpl-dev-portal/tree/IA.v3/content/tutorials/use-specialized-payment-types/use-escrows.
