### ISSUE TITLE
Option server_info is not clickable in Websocket tool

### ISSUE THREAD

**Issue by matejr** [XRPLF/xrpl-dev-portal#123]
Pages like

https://ripple.com/build/websocket-tool/#server_state

show the option "server_info" on the left side. 

But this option (link) is not clickable. Cursor doesn't change when I hover over it. 

I can click on the right part of letter "o" (last character of text "server_info").

Browsers: Chrome 41.0.2272.101 m and Firefox 36.0.1.

**Comment by mDuo13** [comment]
Fixed today. (No commit because the fix was in another repo.)
