### ISSUE TITLE
typo of sidechain visibility?

### ISSUE THREAD

**Issue by tequdev** [XRPLF/xrpl-dev-portal#1260]
https://github.com/XRPLF/xrpl-dev-portal/blob/e5acdb8704e9e84c55bcddbcd90df5de401a3ad0/content/concepts/consensus-network/federated-sidechains.md?plain=1#L33
> Transactions within the sidechain are not visible to the servers on the sidechain. 

#

I think sidechain are visible to the servers on the sidechain, and sidechain are not visible to the servers on the mainchain

I think the sentence below is correct, don't you?

> Transactions within the sidechain are not visible to the servers on the ***mainchain***.

**Comment by amarantha-k** [comment]
Thanks for catching the typo, @develoQ! Will fix it shortly.
