### ISSUE TITLE
Funding for 1st project

### ISSUE THREAD

**Issue by SedatedLikeMindS** [XRPLF/xrpl-dev-portal#1276]
H
.

**Comment by wojake** [comment]
Stop posting random issues lol

**Comment by SedatedLikeMindS** [comment]
I guess I'm really new at this.

**Comment by mDuo13** [comment]
This looks like spam. Please provide more details if you are going to open issues to this repo.

**Comment by SedatedLikeMindS** [comment]
I'm sorry maybe I need to go back and try test again. I'm an artist and
designer with no team and been trying to learn how to NFT my digital art
and tokenize my fashion projects but has been embarringing to say the
least, sorry to all of you  tech-savy developers if I'm looking like a fish
out of water here but I'm trying.

Carrie G.

**Comment by wojake** [comment]
@SedatedLikeMindS Feel free to test out NFTs on the testnet: https://github.com/calvincs/xrpl-nft-creator
I don't know if it works since I'm not into NFTs but good luck.

**Comment by SedatedLikeMindS** [comment]
Appreciate thanks.

**Comment by SedatedLikeMindS** [comment]
Thanks, I'll check it out.
