### ISSUE TITLE
XRPL's testnet explorer

### ISSUE THREAD

**Issue by wojake** [XRPLF/xrpl-dev-portal#1282]
Could you guys add a lists of tokens on the testnet page? There's a list of tokens on the mainnet [page](https://mainnet.xrpl.org/tokens).

This would be beneficial to devs who want to add random trustlines and start issuing DeX Offers from there on, https://github.com/XRPLF/xrpl-dev-portal/issues/1185 would also benefit from this.

**Comment by mDuo13** [comment]
Please send issues with the Explorer to this repo: https://github.com/ripple/explorer/issues/
