### ISSUE TITLE
Wordpress plugin implementation

### ISSUE THREAD

**Issue by IlDuca84** [XRPLF/xrpl-dev-portal#1287]
Hello,
Could be useful to allow to Set the issued token as payment currency.

Example: If I have issued a token, could use this plugin to receive payment in that currency.

Could be useful to add even on link requests: 

https://xumm.app/detect/request:rxxxxxxx?amount=25&currency=token

**Comment by mDuo13** [comment]
I agree that a Wordpress plugin for handling XRPL payments could be pretty cool. Maybe that would be a good idea for an [XRPL Grants](https://xrplgrants.org/) project! However, I think it's a bit too specific for this project, which contains general documentation on the XRP Ledger.
