### ISSUE TITLE
Add Xrplorer's forensics services to xrpl.org explorer

### ISSUE THREAD

**Issue by wojake** [XRPLF/xrpl-dev-portal#1293]
I believe adding Xrplorer's forensic services to the explorer would greatly reduce the amount of scammed victims, it would also increase the XRP Ledger's transparency.

When someone searches for an address (activated or not), refer to Xrplorer's forensic DB which contains a list of reported accounts and display something similar to this:

![image](https://user-images.githubusercontent.com/87929946/149080324-24c859e5-7eec-4080-96b3-8411efe31a75.png)

I've suggested this to xrpscan.com and would hope to see such thing being implemented in xrpl.org, thank you.

Links:
- https://xrplorer.com/
- https://xrplorer.com/products/advisorylist

**Comment by mDuo13** [comment]
I think this is a good idea, so I ported this issue over to the explorer repo for that team's consideration.
