### ISSUE TITLE
Print style for code snippets are broken

### ISSUE THREAD

**Issue by gnurag** [XRPLF/xrpl-dev-portal#1294]
When I print the code snippets from xrpl.org docs, I see blocks of black ink. It would be great to be able to print the docs, and read it away from the screen. Perhaps `<pre>` and `<code>` blocks could use a print friendly style.

![xrpl-print](https://user-images.githubusercontent.com/13650/149333408-e375e390-3d64-4467-a834-f0b321a6ceb1.png)

**Comment by mDuo13** [comment]
Huh, I thought [we fixed that](https://github.com/XRPLF/xrpl-dev-portal/pull/1066), and when I try doing a print preview, it doesn't look like that for me...

![2022-01-14_154151_621010421](https://user-images.githubusercontent.com/7515597/149598782-29d89942-f734-44ed-bc49-2e7ba37de664.png)

(We can and should remove the copy button from the print view, but the rest looks pretty OK to me.)

What browser/OS are you using? Would like to reproduce and fix this.

**Comment by gnurag** [comment]
@mDuo13 I'm on Firefox 95 for Linux (Fedora). I just double checked it on Chrome, and it previewed fine. So this issue is probably limited to Firefox. I don't have macOS or Windows nearby to test.

![xrpl-print-chrome](https://user-images.githubusercontent.com/13650/150000621-96bbfae0-e44b-41ba-b0b2-8ede7a9b28e5.png)

**Comment by mDuo13** [comment]
I'm on Firefox 94 on Arch Linux, so unless the issue is new to Firefox 95 specifically, it's not a Firefox issue. We'll have to dig deeper.

**Comment by mDuo13** [comment]
P.S. while we're fixing the print CSS, the top banner should not print either.

**Comment by mDuo13** [comment]
The print CSS for the new site seems better.
