### ISSUE TITLE
Xrpl services airdrop script

### ISSUE THREAD

**Issue by IlDuca84** [XRPLF/xrpl-dev-portal#1299]
Hello,

Someone could te ti me if there is a script that I could use to send multiple payments over the trustlines (airdrop)?

Thank you

**Comment by mDuo13** [comment]
I am not familiar with such a script, and I agree with [Thomas Silkjær's assessment that most XRPL "airdrops" are ill-advised](https://mobile.twitter.com/Silkjaer/status/1453979705732894726) for reasons described in that thread, so I am cautious about offering / recommending one.
