### ISSUE TITLE
Update AccountSet with instructions for setting a Minter

### ISSUE THREAD

**Issue by JST5000** [XRPLF/xrpl-dev-portal#1305]
Had an issue come up today where someone was trying to mint on behalf of someone else, but couldn't get the account to have a minter field and was unable to figure out why. So, it'd be nice to have that on the AccountSet page with an experimental tag.

For more context, with XLS-20d, if you're trying to allow someone else to mint on your behalf, you need to set two things on your account:
1. You need to enable the `asfAuthorizedMinter` flag (value = 10)
2. You need to set the `minter` field to be the account you want to allow to mint on your behalf

Some of the client libraries help out with this. Ex. xrpl-py requires that you do both of these things at the same time (It'll complain if you try to set `minter` without having asfAuthorizedMinter in the `setFlags` field and vice versa)

It'd be great to add this requirement with the `Experimental` tag to the [AccountSet reference page](https://xrpl.org/accountset.html)

**Comment by mDuo13** [comment]
Related, there is also at least one new [tem code](https://xrpl.org/tem-codes.html), `temBAD_TRANSFER_FEE`.

Note, this is separate from `temBAD_TRANSFER_RATE` which refers to the `TransferRate` field on trust lines. NFTs uses `TransferFee` (4 digits instead of 15) for transfer fees.

**Comment by mDuo13** [comment]
I think the `minter` field is actually `MintAccount` in the AccountSet & AccountRoot by the way.

**Comment by 4499212011** [comment]
Yes I believe someone is trying to access my account

**Comment by martypaz** [comment]
> I think the `minter` field is actually `MintAccount` in the AccountSet & AccountRoot by the way.

The XLS documentation was wrong, it is actually "Minter"

`{
				"SetFlag":javaCast("long", 10),
				"Minter": request.systemMintAddress.address,
				"Account": session.walletAddress,
				"TransactionType":"AccountSet"
			}`

**Comment by mDuo13** [comment]
This is done (and updated for the field being renamed NFTokenMinter in 1.9.x)
