### ISSUE TITLE
"Build a JavaScript Wallet" tutorial

### ISSUE THREAD

**Issue by mDuo13** [XRPLF/xrpl-dev-portal#1308]
- Roughly the same spec as the "Build a Desktop Wallet in Python"  tutorial, but adapted to JavaScript.
- For browsers and/or desktop apps (desktop JS is a little weird but very common these days).
- Maybe some discussion of mobile? TBD.
- No need to handle multi-threading. Async functions are a pretty standard part of JS now and there's no GUI event loop to clash.
- Instead, the UI parts will require more HTML/CSS knowledge.
- Stretch goals: TypeScript stuff

**Comment by intelliot** [comment]
Perhaps this would be a good project for a [bounty](https://github.com/XRPLBounties)?

**Comment by DennisDawson** [comment]
What hasn't been covered in the Quickstart tutorial can be covered in a future Quickstart tutorial.
