### ISSUE TITLE
Ledger.Exposed/XRP Rich List is no longer available

### ISSUE THREAD

**Issue by ImKelp** [XRPLF/xrpl-dev-portal#1321]
## Issue
Unfortunately Ledger Exposed is no longer available and will need to be removed from`Home/Documentation/Dev-Tools/More-Tools` section.

## Screenshot from the Ledger.Exposed Previously: the XRPL Rich List site
![Screenshot 2022-02-20 at 14 41 45](https://user-images.githubusercontent.com/64978825/154848126-1afb4f42-a030-4f55-ae5b-b13a273ccdd0.png)

**Comment by 4499212011** [comment]
Half Baked Users. WOW very PROFESSIONAL of u, but understood.

**Comment by ImKelp** [comment]
> Half Baked Users. WOW very PROFESSIONAL of u, but understood.
> […](#)

Sorry but I'm confused by your response, is my issue of poor quality? This is the first time I've submitted an issue to a public repository so I'm not sure what  etiquettes are required for submitting issues.

**Comment by 4499212011** [comment]
No No that was a ACCIDENT. ALL APOLOGIES. THAT WASN'T SUPPOSE TO BE AT YOU.
AGAIN APOLOGIZE.

**Comment by mDuo13** [comment]
@ColdBio Thanks for reporting the issue. (I don't know who @4499212011 is, but looks like they posted here by mistake.) I've opened a PR to remove the listing.
