### ISSUE TITLE
"ledger" command for rippled takes "binary" switch (which is currently undocumented)

### ISSUE THREAD

**Issue by MarkusTeufelberger** [XRPLF/xrpl-dev-portal#133]
https://ripple.com/build/rippled-apis/#ledger, see the cpp code for how it works.

**Comment by mDuo13** [comment]
Already on my to-do list. On my first pass (looking at the code a week or two ago actually) I wasn't able to get it to work though.

**Comment by MarkusTeufelberger** [comment]
The switch is called "binary" and accepts a boolean as parameter (similar to "full" or the other ones). It defaults to false, see https://github.com/ripple/rippled/blob/master/src/ripple/rpc/handlers/Ledger.cpp#L57

**Comment by mDuo13** [comment]
The output from the command appears to be identical either way. I don't actually see the binary results anywhere.

**Comment by mDuo13** [comment]
continuing task here: https://ripplelabs.atlassian.net/browse/DEV-129
