### ISSUE TITLE
System Requirements

### ISSUE THREAD

**Issue by axmcca** [XRPLF/xrpl-dev-portal#1348]
In the system requirements documentation there is the following statement

`Minimum 50 GB for the database partition. Do not use Amazon Elastic Block Store (AWS EBS) because its latency is too high to sync reliably.`

Then this is followed by

`10,000 IOPS sustained `

However if we take AWS Ebs io1, io2 and gp3 can have higher than 10,000 iops sustained. 

Is this just old doumentation, or is there are good reason for not using ebs.

**Comment by cjcobb23** [comment]
It doesn't matter the IOPs, the latency of EBS is just too high to reliably sync.

**Comment by mDuo13** [comment]
Closing this since it doesn't seem like the existing docs are correct.
