### ISSUE TITLE
Devs needed to implement nft minting to a marketplace (paid job)

### ISSUE THREAD

**Issue by IlDuca84** [XRPLF/xrpl-dev-portal#1351]
Hello,
Is there someone able to develop this function for us?

Please contact me
Thanks

**Comment by mDuo13** [comment]
This issue board is for documentation tasks, bugs, and requests regarding the XRP Ledger and related technology.

This is not intended for recruiting developers, sorry. You may have some more success on other platforms like Discord, [XRPChat](https://www.xrpchat.com/), etc.
