### ISSUE TITLE
Add Ripple.txt validator

### ISSUE THREAD

**Issue by matejr** [XRPLF/xrpl-dev-portal#138]
According to

https://wiki.ripple.com/Ripple.txt

there should be a ripple.txt validator at

https://ripple.com/tools/txt/

But instead of a validator I get a nice picture of JoelKatz and 404.

**Comment by mDuo13** [comment]
This got lost in a website update a while back. I opened a ticket to try and get it restored, but very few people still have access to the original code. I'll update if I get any news on this.

**Comment by mDuo13** [comment]
We found it. The validator has been restored to https://ripple.com/build/ripple-txt-validator/ and the wiki page has been edited accordingly.
