### ISSUE TITLE
Missing documentation for endpoints exchange_rates and normalize

### ISSUE THREAD

**Issue by matejr** [XRPLF/xrpl-dev-portal#140]
https://data.ripple.com/v2/exchange_rates/XRP/USD+rMwjYedjc7qqtKYVLiAccJSmCwih4LnE2q

https://data.ripple.com/v2/normalize?amount=2000&currency=XRP&exchange_currency=USD&exchange_issuer=rMwjYedjc7qqtKYVLiAccJSmCwih4LnE2q

Why are these endpoints not documented? Are you planning to remove them?

**Comment by mDuo13** [comment]
They are in development and may return inaccurate results for now.

**Comment by mDuo13** [comment]
https://ripple.com/build/data-api-v2/#get-exchange-rates
https://ripple.com/build/data-api-v2/#normalize
