### ISSUE TITLE
Incorrect Meta Data For ModifyNode/DeleteNode

### ISSUE THREAD

**Issue by xonuzofa** [XRPLF/xrpl-dev-portal#1428]
I have several examples of this but here is an example.  Why does the Ripple State Difference (Prev - Final Balance) **NOT** equal Prev - Final Values of Order?

**Hash: "70223030B53D8F2B54F3495336E5A84CF08795C711CCD87684105853E6929CFA"
Address in concern: "rL34ui85z9zi7S7oC4UR5uKKsPX5x8D99c"**

**Ripple State: Previous Balance:  "217.070416701"
Ripple State: Final Balance: "0.403965763063"
Ripple State: Difference Balance: "216.6664509379"**

**Offer: Previous Value: "216.450000937"
Offer: Final Value: "0"
Offer: Difference Value: "216.450000937"**

`
{
                "ModifiedNode" : {
                    "FinalFields" : {
                        "Balance" : {
                            "currency" : "78436F696E000000000000000000000000000000",
                            "issuer" : "rrrrrrrrrrrrrrrrrrrrBZbvji",
                            "value" : "-0.403965763063"
                        },
                        "Flags" : NumberInt(2228224),
                        "HighLimit" : {
                            "currency" : "78436F696E000000000000000000000000000000",
                            "issuer" : "rL34ui85z9zi7S7oC4UR5uKKsPX5x8D99c",
                            "value" : "9935587.206356386"
                        },
                        "HighNode" : "12f",
                        "LowLimit" : {
                            "currency" : "78436F696E000000000000000000000000000000",
                            "issuer" : "rXCoYSUnkpygdtfpz3Df8dKQuRZjM9UFi",
                            "value" : "0"
                        },
                        "LowNode" : "b69"
                    },
                    "LedgerEntryType" : "RippleState",
                    "LedgerIndex" : "3033CBD9597C50F7A293152C3B21CDD0551975950C8F48758D1864DB25CA1929",
                    "PreviousFields" : {
                        "Balance" : {
                            "currency" : "78436F696E000000000000000000000000000000",
                            "issuer" : "rrrrrrrrrrrrrrrrrrrrBZbvji",
                            "value" : "-217.070416701"
                        }
                    },
                    "PreviousTxnID" : "EE4666E655C8A7166017D96780CA111E1607CEFE3105F4D222DF55F2F158BB0F",
                    "PreviousTxnLgrSeq" : NumberInt(72015790)
                }
            },
`

`{
                "DeletedNode" : {
                    "FinalFields" : {
                        "Account" : "rL34ui85z9zi7S7oC4UR5uKKsPX5x8D99c",
                        "BookDirectory" : "34DCBAC3A25D7277B5CE0134169410A6E1E20384619085985A0834EF5285A086",
                        "BookNode" : "0",
                        "Flags" : NumberInt(0),
                        "OwnerNode" : "134",
                        "PreviousTxnID" : "98B7010684C7D947EBD1EA811CB648B7D258A07678E4E2C59620ACB025A45726",
                        "PreviousTxnLgrSeq" : NumberInt(72016650),
                        "Sequence" : NumberInt(68767792),
                        "TakerGets" : {
                            "currency" : "78436F696E000000000000000000000000000000",
                            "issuer" : "rXCoYSUnkpygdtfpz3Df8dKQuRZjM9UFi",
                            "value" : "0"
                        },
                        "TakerPays" : "0"
                    },
                    "LedgerEntryType" : "Offer",
                    "LedgerIndex" : "BF699CFE34AFCE83F02183190BA166F14482FC39A733F5F176693A8F3AA46F77",
                    "PreviousFields" : {
                        "TakerGets" : {
                            "currency" : "78436F696E000000000000000000000000000000",
                            "issuer" : "rXCoYSUnkpygdtfpz3Df8dKQuRZjM9UFi",
                            "value" : "216.450000937"
                        },
                        "TakerPays" : "50000000"
                    }
                }
            },`

**Comment by LimpidCrypto** [comment]
The issuer rXCoYSUnkpygdtfpz3Df8dKQuRZjM9UFi has set a 0.1 % transfer rate.
216.6664509379 / 1.001 = 216.450000937

**Comment by mDuo13** [comment]
Thanks for answering this one, @LimpidCrypto.

For more information, see the docs on [Transfer Fees](https://xrpl.org/transfer-fees.html).
