### ISSUE TITLE
Improve hover contrast on search selection in docs page (in dark mode)

### ISSUE THREAD

**Issue by bugsbunnies** [XRPLF/xrpl-dev-portal#1432]
Proposing a more accessible gray (#454549) on the hover selection while searching for content in the docs page (dark mode only).

**Comment by mDuo13** [comment]
That suggested gray is available as `$gray-600` in the SCSS by the way

**Comment by mDuo13** [comment]
The search window has changed but the problem is still there. The blue highlight color (`--search-highlight-text-color`, `#1F7CFF`) doesn't have enough contrast against the dark gray background (`--search-input-bg-color`, `#22242B`) in dark mode.

![(Screenshot showing a search for dUNL](https://github.com/user-attachments/assets/91fcd9bb-0111-49e1-a4bc-e024bb15d87c)

[Contrast checker](https://webaim.org/resources/contrastchecker/) reports 3.97:1. We should aim for WCAG AAA standard for normal, small text (7:1 contrast)

**Comment by bugsbunnies** [comment]
> Contrast checker



> The search window has changed but the problem is still there. The blue highlight color (`--search-highlight-text-color`, `#1F7CFF`) doesn't have enough contrast against the dark gray background (`--search-input-bg-color`, `#22242B`) in dark mode.
> 
> ![(Screenshot showing a search for dUNL](https://private-user-images.githubusercontent.com/7515597/348401608-91fcd9bb-0111-49e1-a4bc-e024bb15d87c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA4MjQyNjksIm5iZiI6MTcyMDgyMzk2OSwicGF0aCI6Ii83NTE1NTk3LzM0ODQwMTYwOC05MWZjZDliYi0wMTExLTQ5ZTEtYTRiYy1lMDI0YmIxNWQ4N2MucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MTJUMjIzOTI5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODA4MmYxY2VlMzE4YjZkOGRiM2U0NTNiZGEzY2I4MDBmYjczYjIyYmFjYjYzZGYxMzgxNjJhYTVmZjlmY2I4MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.6FliRp73zZVDqDyqueaSWc8n7fekkwgSD2b6CLqtYP0)
> 
> [Contrast checker](https://webaim.org/resources/contrastchecker/) reports 3.97:1. We should aim for WCAG AAA standard for normal, small text (7:1 contrast)

Blue-purple-30 (#B480FF) can be an alternative?

**Comment by amarantha-k** [comment]
The blue-purple-30(#B480FF) shade looks pretty close to the color used for links (#9A52FF).

**Comment by bugsbunnies** [comment]
> The blue-purple-30(#B480FF) shade looks pretty close to the color used for links (#9A52FF).

I think that's okay since they'll most likely be interacting with the results and highlighting it is just a way to separate out the relevant text from the rest. Looking at some mocks for the Docs page they were also in the lighter purple shade, what do you think?
<img width="650" alt="image" src="https://github.com/user-attachments/assets/5a5611a1-f3ee-46de-ae29-6e4e8050bdd6">
