### ISSUE TITLE
Lack of contrast in DepositAuth table (in light mode)

### ISSUE THREAD

**Issue by intelliot** [XRPLF/xrpl-dev-portal#1434]
https://xrpl.org/depositauth.html#precise-semantics

<img width="1381" alt="Screen Shot 2022-07-15 at 3 16 35 PM" src="https://user-images.githubusercontent.com/81505/179318509-eb56526f-73c0-46ea-8aee-8eb702bc1a4d.png">

In light mode, some text is hard to read because it's black on dark gray.

**Comment by dvyanc** [comment]
Thanks
