### ISSUE TITLE
server_info endpoint documentation error

### ISSUE THREAD

**Issue by gmosx** [XRPLF/xrpl-dev-portal#1446]
In the documentation of the `server_info` endpoint, it's stated that `state_accounting.*.transitions` is Number, when in fact in the server response it is a String.

Additionally, the field `peers` seems to be either optional or deprecated/removed.

**Comment by mDuo13** [comment]
That is true about `state_accounting`.

As for `peers`, I believe the difference is whether you're connected to a reporting mode server. If you use s1.ripple.com, which is (I think) all reporting mode servers right now, the response omits it. If you use xrplcluster.com, which is all p2p mode servers, the response includes it.

Can update the docs with this.

**Comment by gmosx** [comment]
Thank you!
