### ISSUE TITLE
Problem: historical data loss after node restart

### ISSUE THREAD

**Issue by 1143857824** [XRPLF/xrpl-dev-portal#1448]
**Problem:** historical data loss after node restart
**Expected result:** it is hoped that the data after the time when the node is first built can be retained, and the previous data will not be lost even if it is restarted

**How to configure nodes to achieve this purpose？**

The following is our current node setup configuration, but there is this problem at present

> rippled.cfg
    
    [server]
    port_rpc_admin_local
    port_peer
    port_ws_admin_local
    
    [port_rpc_admin_local]
    port = 5005
    ip = 0.0.0.0
    admin = 0.0.0.0
    protocol = http
    
    [port_peer]
    port = 51235
    ip = 0.0.0.0
    #ip = ::
    protocol = peer
    
    [port_ws_admin_local]
    port = 6006
    ip = 0.0.0.0
    admin = 0.0.0.0
    protocol = ws
    
    [node_size]
    medium
    
    [node_db]
    type=NuDB
    path=/var/lib/rippled/db/nudb
    online_delete=81920000
    advisory_delete=0
    
    [database_path]
    /var/lib/rippled/db
    
    [debug_logfile]
    /var/log/rippled/debug.log
    
    [sntp_servers]
    time.windows.com
    time.apple.com
    time.nist.gov
    pool.ntp.org
    
    
    [validators_file]
    validators.txt
    
    [rpc_startup]
    { "command": "log_level", "severity": "warning" }
    
    [ssl_verify]
    1

**Comment by LimpidCrypto** [comment]
This is not an issue of the dev portal. Please search in the [rippled](https://github.com/XRPLF/rippled) repo if there were people who already had similar issues, otherwise open a new issue there.
