### ISSUE TITLE
Switch focus to search <input />

### ISSUE THREAD

**Issue by ledhed2222** [XRPLF/xrpl-dev-portal#1453]
When I click the magnifying glass, which brings up the search <input />, I don't expect to have to click within that <input /> to start typing my query.

**Comment by mDuo13** [comment]
This works as expected for me already. Are you talking about the top search bar? What platform?

**Comment by ledhed2222** [comment]
I found it - it's in the blog. For example: https://xrpl.org/blog/2022/nft-devnet-reset.html#further-reading

**Comment by DennisDawson** [comment]
This issue rendered moot after transition to redocly.
