### ISSUE TITLE
Binary blob format is not documented

### ISSUE THREAD

**Issue by matejr** [XRPLF/xrpl-dev-portal#148]
Please add specs at least for transactions.

**Comment by mDuo13** [comment]
This is difficult, but I'll put it on my backlog.

**Comment by matejr** [comment]
Maybe you can create docs in phases. First phase could be just general overview + links to reference implementation (ripple-binary-codec?).

**Comment by mDuo13** [comment]
I have (finally?) started making progress on this: https://github.com/mDuo13/ripple-dev-portal/tree/txserialization
