### ISSUE TITLE
Update Content on Amendments

### ISSUE THREAD

**Issue by biasgooseRX** [XRPLF/xrpl-dev-portal#1485]
The content on the [Amendments Page](https://xrpl.org/amendments.html) needs some updating:

"An amendment normally requires 80% support for two weeks before it can apply." 

update to reflect that amendments require at least more than 80% (>80%)

-----------

"The tfGotMajority flag means that support for the amendment has increased to at least 80% of trusted validators.
The tfLostMajority flag means that support for the amendment has decreased to less than 80% of trusted validators."

update to reflect that amendments require at least more than 80% (>80%)

**Comment by wojake** [comment]
https://github.com/XRPLF/xrpl-dev-portal/pull/1491
