### ISSUE TITLE
Ripple REST example for signing transactions returns HTTP error 400 Bad Request

### ISSUE THREAD

**Issue by matejr** [XRPLF/xrpl-dev-portal#151]
Default example at:

https://ripple.com/build/rest-tool/#sign-transaction

returns "400 Bad Request":

```
{
  "success": false,
  "error_type": "invalid_request",
  "message": "Invalid secret",
  "error": "restINVALID_PARAMETER"
}
```

**Comment by mDuo13** [comment]
This is by design -- the examples all have the wrong secret included. Sharing the secret to an actual, existing account is a recipe for chaos. You should substitute your own test credentials for the account and secret.
