### ISSUE TITLE
Textbox for editing "Sign Transaction" JSON in Ripple-REST Tool is not visible

### ISSUE THREAD

**Issue by matejr** [XRPLF/xrpl-dev-portal#152]
See screenshot of

https://ripple.com/build/rest-tool/#sign-transaction

Sometimes it opens when I click several times on it.

![ripplerestsignmissingfield](https://cloud.githubusercontent.com/assets/34675/12059218/81cd1792-af57-11e5-882e-2fcd699bd527.png)

**Comment by mDuo13** [comment]
This is a known bug. You can work around it by clicking another method and back. A while back I spent a couple days trying to track down the cause of it, couldn't find anything, and gave up. (The behavior doesn't seem to occur on our staging or dev environments.)

**Comment by matejr** [comment]
Ok, thanks, I'm closing this. Clicking on other method works reliably.
