### ISSUE TITLE
Add `nft_offer` type to `account_objects`  Request Format

### ISSUE THREAD

**Issue by tequdev** [XRPLF/xrpl-dev-portal#1520]
[account_objects page](https://xrpl.org/account_objects.html#request-format)

https://github.com/XRPLF/rippled/blob/610436d737a03925febde7e6aab7e81add06b3ab/src/ripple/rpc/impl/RPCHelpers.cpp#L908

**Comment by DennisDawson** [comment]
PR https://github.com/XRPLF/xrpl-dev-portal/pull/1671
