### ISSUE TITLE
XCode link incorrect

### ISSUE THREAD

**Issue by mvadari** [XRPLF/xrpl-dev-portal#1529]
Link located on this page: https://xrpl.org/build-run-rippled-macos.html

Currently is: https://developer.apple.com/download/

Should be: https://developer.apple.com/xcode/

**Comment by mDuo13** [comment]
Ironically the `/download/` link is actually the URL in the call-to-action button at the bottom of the XCode page, but it takes you to an Apple Developer ID login page, so that's confusing. I agree changing the link as you suggest is an improvement.
