### ISSUE TITLE
Faucet page doesn't show up in search

### ISSUE THREAD

**Issue by mvadari** [XRPLF/xrpl-dev-portal#1530]
I was looking for https://xrpl.org/xrp-testnet-faucet.html, and I tried searching `Faucet` in the search. The places where the link shows up in "See More" showed up in the search results, but not this page itself.

**Comment by mDuo13** [comment]
Verified that this happens but I don't think we have any control over it with our current search tool. Hopefully after we switch toolchains this won't happen on the new toolchain's search.
