### ISSUE TITLE
Update stack model diagram

### ISSUE THREAD

**Issue by mvadari** [XRPLF/xrpl-dev-portal#1531]
The diagram: 
![image](https://user-images.githubusercontent.com/8029314/192638400-f05ad6b8-6d85-48b2-b2b6-9d9b16442adb.png)

This contains the Data API and ripple-lib as elements - those should be updated to the current services offered.

Located at: https://xrpl.org/software-ecosystem.html#stack-levels

**Comment by DennisDawson** [comment]
Done
