### ISSUE TITLE
Add JSON example of NFTokenAcceptOffer to transaction reference

### ISSUE THREAD

**Issue by mDuo13** [XRPLF/xrpl-dev-portal#1553]
Unlike most of the transaction type pages, [NFTokenAcceptOffer](https://xrpl.org/nftokenacceptoffer.html) is missing the example JSON. That should be fixed ASAP.

**Comment by LimpidCrypto** [comment]
Same applies for the [NFTokenOffer](https://xrpl.org/nftokenoffer.html) object.
