### ISSUE TITLE
Why no seed when generating wallet when using fromMnemonic()

### ISSUE THREAD

**Issue by Muhammad-1990** [XRPLF/xrpl-dev-portal#1557]
Why is there no seed value when generating a wallet using
`play note spell cook grain enroll visa snake fall pass differ bag crumble market eternal vocal visit normal silver bench wild average symbol broccoli`
`const wallet = xrpl.Wallet.fromMnemonic(mnemonic)`
`await client.fundWallet(wallet)`
`console.log(wallet)`
response: 
`
Wallet {
   publicKey: '0248E4DDB829E860E8FD75613EB67BDE1F15340210D3B860D8B5E32872C1772936',
   privateKey: '001EA10B0270AEAAC26B88339B216FADFD318525E98DFFF398198750F55034BCD4',
   classicAddress: 'raAD3fgAxTFVhMUmFcJqeLVbYauQ9eeyy2',
   seed: undefined
}
`

I'm new and playing around with generating wallets and regenerating using the mnemonic phrases.
is this the correct way?
what is the preferred way of creating a wallet and generating the mnemonic?

thanks,

**Comment by mDuo13** [comment]
This looks like an [xrpl.js](https://github.com/XRPLF/xrpl.js/) question. You might get an answer if you ask there. Sorry, this repo is only for the xrpl.org website.
