### ISSUE TITLE
how to purchase xrp?

### ISSUE THREAD

**Issue by Muhammad-1990** [XRPLF/xrpl-dev-portal#1559]
if i create an exchange, where and how do i purchase xrp?

**Comment by wojake** [comment]
i use a fax machine.

![image](https://user-images.githubusercontent.com/87929946/200586482-d26eab1e-96f2-4c62-90cf-4166ad916c49.png)

**Comment by intelliot** [comment]
https://www.google.com/search?q=how+to+purchase+xrp

**Comment by Muhammad-1990** [comment]
Read the question you dumb twats!! Not as an ordinary user. As a freaking exchange! Where and how did the first exchange get it from! Don’t reply if you don’t know the answer.

**Comment by intelliot** [comment]
Exchanges generally do not purchase XRP. The users of an exchange are trading XRP with other users (often market makers, which are just a type of user/trader). The XRP comes from user (customer) deposits. There are many ways for those users to get XRP, most of which can be discovered via the link provided.

**Comment by intelliot** [comment]
Also potentially relevant to your question - [this page explains where XRP originates](https://xrpl.org/xrp.html).
