### ISSUE TITLE
Filtering `ledger_entry` by `nft_page` isn't mentioned

### ISSUE THREAD

**Issue by mvadari** [XRPLF/xrpl-dev-portal#1580]
Here is a command that works on mainnet but isn't mentioned on the `ledger_entry` page: https://xrpl.org/websocket-api-tool.html?server=wss%3A%2F%2Fs2.ripple.com%2F&req=%7B%22id%22%3A%22example_get_accountroot%22%2C%22command%22%3A%22ledger_entry%22%2C%22nft_page%22%3A%2205BDF50FBDEF54276A1C889252E71B4347C3A0BD2EA530C4BADAE7EC00000B63%22%2C%22ledger_index%22%3A%22validated%22%7D

**Comment by DennisDawson** [comment]
Changes merged 
https://github.com/XRPLF/xrpl-dev-portal/issues/1580
