### ISSUE TITLE
UNLModify Header Appears Twice

### ISSUE THREAD

**Issue by JST5000** [XRPLF/xrpl-dev-portal#1590]
On the UNLModify page the "UNL Modify Fields" header appears twice. (Including two unique in-page links)

It doesn't seem to be an error in the markdown as far as I can tell, so maybe something happens after that? 

Not sure if this issue is affecting other pages.

https://xrpl.org/unlmodify.html#unlmodify-fields

<img width="1364" alt="image" src="https://user-images.githubusercontent.com/19694186/202578945-06cc8fcc-751a-47a3-ae82-1c6b12282620.png">

**Comment by ckniffen** [comment]
It is because the page defines the header and so does the snippet that is included right after it.  https://github.com/XRPLF/xrpl-dev-portal/blob/master/content/_snippets/pseudo-tx-fields-intro.md

**Comment by Island-Ghost** [comment]
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
