### ISSUE TITLE
Add section on NFToken Reserves

### ISSUE THREAD

**Issue by mDuo13** [XRPLF/xrpl-dev-portal#1591]
Related: #1124

The [Reserves page](https://xrpl.org/reserves.html) doesn't mention NFTs at all, and it should. In fact, it might need a whole section or at least a paragraph about it because the way NFTokens contribute to your reserve requirement is a bit unintuitive and somewhat unpredictable. Notably, it's not a simple linear relationship between the number of NFTs you own and your reserve requirements for them. See [this discussion](https://github.com/XRPLF/XRPL-Standards/discussions/46#discussioncomment-4079975) for more info on how the reserves work in practice, the challenges users have with that, and some ideas of how to describe it simply to users.

The NFTokenPage entry reference has [a section on reserves](https://xrpl.org/nftokenpage.html#the-reserve-in-practice) but it doesn't cover this information and it's harder to find than the Reserves page. The table of effective reserves "per NFT" is probably misleading (the 64 NFTs column is impossible!) and contains unnecessary information—it has rows for the current incremental reserve and two other possible values for owner reserves that are not in effect; I'm sure the idea is to show how it would change if the reserve changed via fee voting, but I feel that may be more confusing than helpful.

A more useful table might show a range of possible reserve values (maybe "typical" to "best case") for given numbers of NFTs using the current owner reserve (2 XRP per object owned). For example, with 63 NFTs it's likely you'll have anywhere from 2 to 4 NFTokenPage objects leading to reserves from 4 to 8 XRP (which adds up to effectively 0.126 to 0.063 XRP per NFT, but practically speaking you aren't charged per NFT, you're charged per page and that's what users need to know).

**Comment by mDuo13** [comment]
Did some of this while I was fixing some spelling/style reports in the same file in #1615

**Comment by DennisDawson** [comment]
Issues addressed.
