### ISSUE TITLE
Fix broken remote links

### ISSUE THREAD

**Issue by mDuo13** [XRPLF/xrpl-dev-portal#1599]
Running the link checker on the `master` branch (latest commit: 1d1c48c3195b391e9f4ac9b065ee10115c80d4da) including checking _external_ links returns failures for the following links:

```
File: out/list-your-exchange-on-xrp-charts.html Link: https://xrpcharts.ripple.com/#/xrp-markets
File: out/transaction-metadata.html Link: https://xrpcharts.ripple.com/#/transactions/8C55AFC2A2AA42B5CE624AEECDB3ACFDD1E5379D4E5BF74A8460C5E97EF8706B
File: out/nft_info.html Link: https://github.com/XRPLF/clio/releases/tag/1.1.0
File: out/evm-sidechain-validator-security.html Link: https://docs.tendermint.com/master/nodes/remote-signer.html
File: out/intro-to-evm-sidechain.html Link: https://rpc-evm-sidechain.xrpl.org/
File: out/xrp-overview.html Link: https://ftx.com/
File: out/events.html Link: https://xrplnft2022.devpost.com/
File: out/look-up-transaction-results.html Link: https://xrpcharts.ripple.com/#/transactions/
File: out/look-up-transaction-results.html Link: https://xrpcharts.ripple.com/#/transactions/8C55AFC2A2AA42B5CE624AEECDB3ACFDD1E5379D4E5BF74A8460C5E97EF8706B
File: out/look-up-transaction-results.html Link: https://xrpcharts.ripple.com/#/transactions/C4FE7F5643E20E7C761D92A1B8C98320614DD8B8CD8A04CFD990EBC5A39DDEA2
File: out/join-evm-sidechain-devnet.html Link: https://docs.tendermint.com/master/tendermint-core/using-tendermint.html#persistent-peer
File: out/ja/run-rippled-as-a-validator.html Link: https://xrpcharts.ripple.com/#/validators
File: out/ja/run-rippled-as-a-validator.html Link: https://xrpcharts.ripple.com/#/validators
File: out/ja/list-your-exchange-on-xrp-charts.html Link: https://xrpcharts.ripple.com/#/xrp-markets
File: out/ja/nft_info.html Link: https://github.com/XRPLF/clio/releases/tag/1.1.0
File: out/ja/evm-sidechain-validator-security.html Link: https://docs.tendermint.com/master/nodes/remote-signer.html
File: out/ja/intro-to-evm-sidechain.html Link: https://rpc-evm-sidechain.xrpl.org/
File: out/ja/xrp-overview.html Link: https://ftx.com/
File: out/ja/data-api.html Link: https://xrpcharts.ripple.com/
File: out/ja/events.html Link: https://xrplnft2022.devpost.com/
File: out/ja/look-up-transaction-results.html Link: https://xrpcharts.ripple.com/#/transactions/
File: out/ja/look-up-transaction-results.html Link: https://xrpcharts.ripple.com/#/transactions/8C55AFC2A2AA42B5CE624AEECDB3ACFDD1E5379D4E5BF74A8460C5E97EF8706B
File: out/ja/look-up-transaction-results.html Link: https://xrpcharts.ripple.com/#/transactions/C4FE7F5643E20E7C761D92A1B8C98320614DD8B8CD8A04CFD990EBC5A39DDEA2
File: out/ja/join-evm-sidechain-devnet.html Link: https://docs.tendermint.com/master/tendermint-core/using-tendermint.html#persistent-peer
```

For each of these we should:

1. Check to see if the link resolves in a browser. (Sometimes, Cloudflare protections block our link checker from accessing a site.) If the link works now, check that it works using Python and if it gives an error _only_ from a script, then add the link to the `known_broken_links` in the `dactyl-config.yml`
2. If the link does not resolve in a browser, remove or replace it with the nearest approximate replacement. (For example, most XRPCharts links can probably go to somewhere on the Explorer instead.)
3. Follow up with Ripple's marketing/design people for the broken links on pages like the "XRP Overview" and "Events" page to get a suitable replacement (or updated design without the link) as necessary.

**Comment by ripple369** [comment]
[https://xrpcharts.ripple.com/#/xrp-markets](https://t.co/kqITOkVonW): This link seems to be down or not responding, which is causing the failure.

**Comment by ripple369** [comment]
https://xrpcharts.ripple.com/#/transactions/8C55AFC2A2AA42B5CE624AEECDB3ACFDD1E5379D4E5BF74A8460C5E97EF8706B: This link returns a "Transaction not found" error message, which may indicate that the transaction has been deleted or is not available anymore.

https://github.com/XRPLF/clio/releases/tag/1.1.0: This link seems to be working correctly.

https://docs.tendermint.com/master/nodes/remote-signer.html: This link seems to be working correctly.

https://rpc-evm-sidechain.xrpl.org/: This link seems to be working correctly.

https://ftx.com/: This link seems to be working correctly.

https://xrplnft2022.devpost.com/: This link seems to be working correctly.

https://xrpcharts.ripple.com/#/transactions/: This link seems to be working correctly.

https://docs.tendermint.com/master/tendermint-core/using-tendermint.html#persistent-peer: This link seems to be working correctly.

https://xrpcharts.ripple.com/#/validators: This link seems to be working correctly.

**Comment by amarantha-k** [comment]
These links are working or redirecting to valid URLs and no further action is needed on this issue.
