### ISSUE TITLE
Update docs for ledger RPC to reflect clio does not support full parameter

### ISSUE THREAD

**Issue by cjcobb23** [XRPLF/xrpl-dev-portal#1618]
Clio does not support the full parameter of the ledger RPC. Can we update the docs to reflect this?

**Comment by mDuo13** [comment]
Fixed as part of this commit:

https://github.com/XRPLF/xrpl-dev-portal/commit/845422da7f64b455a0df3c37fbeb84ba49373fed#diff-b78b50ff27338128aa7f89ae9fdbeaed8c8deb25877f9bc56841a4524c3eccfdR70
