### ISSUE TITLE
Change NFToken to NFT (and similar) throughout documentation

### ISSUE THREAD

**Issue by DennisDawson** [XRPLF/xrpl-dev-portal#1628]
While we used NFToken to be consistent with the API early on, NFT is probably the better choice for SEO considerations.

**Comment by mDuo13** [comment]
Don't forget to update the [term in the contributing guidelines](https://github.com/XRPLF/xrpl-dev-portal/blob/master/CONTRIBUTING.md#terminology) with the new preferred usage as part of this task.

**Comment by DennisDawson** [comment]
Done.
