### ISSUE TITLE
Is there any public clio server?

### ISSUE THREAD

**Issue by mahiros-tech** [XRPLF/xrpl-dev-portal#1661]
Hi, I am running my own xrpl quick node, but want to get NFT info from NFT_Token id?
Is it possible to run both quick node, clio servers without any problem in one VPS?
or is there any public clio server overthere?

**Comment by JST5000** [comment]
I'm not sure about public servers, maybe someone else knows more, but as for running it yourself you should be able to do that by following these instructions :) - https://xrpl.org/install-clio-on-ubuntu.html

Step 8 says "If you are running rippled on a separate machine, modify your Clio config file to point to it. You can skip this step if you used the clio package to install both on the same machine." which implies to me that you can run it on the same machine :)

**Comment by mvadari** [comment]
s2.ripple.com now runs Clio nodes.
