### ISSUE TITLE
Cookie preferences causing error in the footer

### ISSUE THREAD

**Issue by hazardcookie** [XRPLF/xrpl-dev-portal#1676]
Was browsing the docs tonight I noticed a cookie icon in the bottom right corner of my screen. Clicked it, saved my preferences and now i keep seeing the following error in the footer of the docs, sometimes it repeats many times in a row.

`Below is the Microsoft Advertising UET tag tracking code. You need to add it to your entire website in the header or body sections. If your website has a master page, then you can add it once there and it is included in all pages. For tips see [http://help.ads.microsoft.com/#apex/3/en/56688/-1](https://urldefense.com/v3/__http://help.ads.microsoft.com/*apex/3/en/56688/-1__;Iw!!PZTMFYE!-V6ZWF_07bZIorr03qqEgSeRkOmHsL0P-wkg1OulUPUqE8TeWKNKEfG7Kh6z3is0pbENvABXf89y3poqDwQ$)` 

Below is what the footer looked like when i scrolled to the bottom after changing settings for the first time. Refreshing it removes the error, but clicking around the site seems to bring it back slowly. 

<img width="859" alt="image" src="https://user-images.githubusercontent.com/116046337/212576304-345cf669-0841-4e8f-aac0-6d0bf28e574b.png">

For context i changed my cookie settings to turn off all cookies besides essential and personalization :)

**Comment by tequdev** [comment]
It appears when switching between the WebSocket/JSON-RPC/Commandline tabs of the Request Format and Response Format.

[https://xrpl.org/tx.html](https://xrpl.org/tx.html)

**Comment by mDuo13** [comment]
This may or may not be related to the Osano cookie management tool, but we should definitely fix it.

Also, we should move the cookie icon or the "jump to top" button so they don't overlap.

**Comment by justinr1234** [comment]
This was not related to Osano. The GTM tracking snippet was incorrectly setup and it was doing 2 things:

1. Inserting the script on every single page click event
2. The script contained both the `<script>` tag and the literal instructions copy pasted from the Microsoft website. It should have only contained the `<script>` tag. This resulted in it inserting the entire `<script>` AND the instructions text at the bottom of the page when GTM loaded and every single time someone clicked on the page.

It has been fixed
