### ISSUE TITLE
Page Toolbar is collapsing.

### ISSUE THREAD

**Issue by tequdev** [XRPLF/xrpl-dev-portal#1713]
The top border of the `Page Toolbar` is hidden (even though it exists) in mobile sizes.

![スクリーンショット 2023-01-29 22 32 49](https://user-images.githubusercontent.com/69445828/215329630-a46a1c1f-fb6f-44b0-94c9-50b3bdfff047.png)

**Comment by amarantha-k** [comment]
This may have been fixed as I see the border around Page Toolbar on iOS. 
@develoQ Please comment if this issue still persists in your environment. Thanks!

**Comment by tequdev** [comment]
Confirmed that it has been fixed.
