### ISSUE TITLE
wrong/missing data at xrpl.org

### ISSUE THREAD

**Issue by Makx164** [XRPLF/xrpl-dev-portal#1720]
The website xrpl.org at the subitem wallets shows a 404:
https://xrpl.org/wallet.html

In Events, an event from December 2022 is listed under upcoming event: 
https://xrpl.org/events.html

**Comment by intelliot** [comment]
Where did you find the link to wallet.html? I'm not aware of that being a page that ever existed.

**Comment by Makx164** [comment]
https://livenet.xrpl.org/

<img width="160" alt="Bildschirm­foto 2023-02-10 um 13 12 45" src="https://user-images.githubusercontent.com/79017801/218089910-f0781eb3-b86c-4900-b03d-926c2c038af4.png">

**Comment by ckniffen** [comment]
Related to https://github.com/ripple/explorer/issues/262
