### ISSUE TITLE
Test harness input field #standbyTransferFeeField should have default value of 0 set to avoid serialization error on NFToken Mint button action

### ISSUE THREAD

**Issue by jremi** [XRPLF/xrpl-dev-portal#1737]
Inside the Quickstart zip, all  HTML file test harnesses related to the input field with id `#standbyTransferFeeField` (related to NFT Transfer Fee field)  should have the value set with default of `0`. 

From playing around with the test harness, it will fail to serialize the transaction blob when attempting to trigger **MintNFToken** button, when this field is not set with a value >= 0.

Alternative option is to set the value via JS, however it just seems easier to do this via the value attribute on the input.

If the HTML files are on the branch I would have submitted a pull request with the change, but I only found them in the compressed zip archive.

**Currently**
```html
<input type="text" id="standbyTransferFeeField" value="" size="80"/>
```

**Suggestion**
```html
<input type="text" id="standbyTransferFeeField" value="0" size="80"/>
```

🙏

**Comment by DennisDawson** [comment]
Addressed in https://github.com/XRPLF/xrpl-dev-portal/pull/2500.
