### ISSUE TITLE
Document node_size in rippled.cfg

### ISSUE THREAD

**Issue by matejr** [XRPLF/xrpl-dev-portal#176]
It is not clear how node_size is supposed to influence the amount of memory consumed by rippled.

[Existing documentation](https://wiki.ripple.com/Rippled_Troubleshooting#.5Bnode_size.5D) looks outdated.

**Comment by mDuo13** [comment]
Noted. Will include this if/when I finally do comprehensive rippled.cfg documentation (it's midway through the backlog).

**Comment by mDuo13** [comment]
This is now documented as part of Capacity Planning. ( [source file](https://github.com/ripple/ripple-dev-portal/blob/master/content/tutorials/manage-the-rippled-server/capacity-planning.md#node-size) | [live site](https://developers.ripple.com/capacity-planning.html#node-size) )
