### ISSUE TITLE
Unclear currency format

### ISSUE THREAD

**Issue by vporton** [XRPLF/xrpl-dev-portal#1765]
https://xrpl.org/account_lines.html has `balance` and `currency` fields.

It is unclear whether here the `currency` can be `XRP`, and if yes, what format `balance` has in this case: value in XRP drops or floating point as usual for non-XRP currencies.

**Comment by legleux** [comment]
There is no concept of an XRP trust line so `account_lines` only provides [token](https://xrpl.org/tokens.html) info, so no, `currency` will not be XRP.

From [account_lines](https://xrpl.org/account_lines.html):
```
The account_lines method returns information about an account's trust lines, including balances in all non-XRP currencies and assets. 
```

Maybe the "including" there is a little misleading?

XRP balances can be obtained from the `Balances` field from `account_data` returned from a request of `account_info`

**Comment by vporton** [comment]
> Maybe the "including" there is a little misleading?

Yes, better wording would be:

> The `account_lines` method returns information about an account's trust lines, that contain balances in all non-XRP currencies and assets.
