### ISSUE TITLE
Incorrect description of deposit on the `AMMWithdraw` page.

### ISSUE THREAD

**Issue by tequdev** [XRPLF/xrpl-dev-portal#1773]
Shouldn't the following section be about Withdraw?

https://github.com/XRPLF/xrpl-dev-portal/blob/90604e1766f03e5c9f43a15ac59ac8acb2cf3140/content/references/protocol-reference/transactions/transaction-types/ammwithdraw.md?plain=1#L60

https://github.com/XRPLF/xrpl-dev-portal/blob/90604e1766f03e5c9f43a15ac59ac8acb2cf3140/content/references/protocol-reference/transactions/transaction-types/ammwithdraw.md?plain=1#L111

https://github.com/XRPLF/xrpl-dev-portal/blob/90604e1766f03e5c9f43a15ac59ac8acb2cf3140/content/references/protocol-reference/transactions/transaction-types/ammwithdraw.md?plain=1#L116

**Comment by mDuo13** [comment]
Fixing this on the other site now that AMM has been moved
