### ISSUE TITLE
Add links to XLS-Standards

### ISSUE THREAD

**Issue by intelliot** [XRPLF/xrpl-dev-portal#1778]
XRPL.org is a hub for developers. Let's add a link to [XRPL-Standards](https://github.com/XRPLF/XRPL-Standards) so that developers can:

- Discover and learn about standards and proposed standards
- Write and propose new standards

https://github.com/XRPLF/XRPL-Standards

**Comment by kennyzlei** [comment]
I believe there is an existing link here https://xrpl.org/contribute-code.html#standards-drafts but I suspect few folks will find it and click through.  I personally find https://github.com/XRPLF/xrpl-dev-portal/issues/1779 as a more impactful investment

**Comment by amarantha-k** [comment]
The Contribution Guide has been updated and includes a link to XLS-Standards - https://xrpl.org/contribute-code-flow.html#xrp-ledger-standards

**Comment by amarantha-k** [comment]
Agree that #1779 will be a more impactful change and we should look at investing time and effort there.
