### ISSUE TITLE
Code samples "Set Minter" bug

### ISSUE THREAD

**Issue by zgrguric** [XRPLF/xrpl-dev-portal#1788]
Set Minter button not working. Unsure if this is xrpl.js bug or code samples bug, or just old version of xrpl.js lib. So reported.

Code samples here: https://github.com/XRPLF/xrpl-dev-portal/blob/master/content/_code-samples/quickstart/js/quickstart.zip

Console:
```
Uncaught (in promise) TypeError: t is undefined
    c https://unpkg.com/xrpl@2.2.3:2
    f https://unpkg.com/xrpl@2.2.3:2
    n https://unpkg.com/xrpl@2.2.3:2
    n https://unpkg.com/xrpl@2.2.3:2
    f https://unpkg.com/xrpl@2.2.3:2
    submitAndWait https://unpkg.com/xrpl@2.2.3:2
    n https://unpkg.com/xrpl@2.2.3:2
    n https://unpkg.com/xrpl@2.2.3:2
    submitAndWait https://unpkg.com/xrpl@2.2.3:2
    oPsetMinter file:///C:/_XRPL_QUICKSTART/ripplex6-authorized-minter.js:109
    onclick file:///C:/_XRPL_QUICKSTART/6.authorized-minter.html:1
```

**Comment by DennisDawson** [comment]
From Caleb Kniffen:
basically anywhere that has
  const signed = my_wallet.sign(prepared);
  const result = await client.submitAndWait(signed.tx_json);

should be:
const signed = my_wallet.sign(prepared);
  const result = await client.submitAndWait(signed.tx_blob);

also the version is pretty old of xrpl.js and if you reference the js this way it will have source maps
<script src='https://unpkg.com/xrpl@2.7.0/build/xrpl-latest-min.js'></script>

**Comment by ckniffen** [comment]
The only file that used `signed.tx_json` is `ripplex6-authorized-minter.js`

**Comment by DennisDawson** [comment]
Addressed in https://github.com/XRPLF/xrpl-dev-portal/pull/1855
