### ISSUE TITLE
Create AMM tutorial

### ISSUE THREAD

**Issue by mDuo13** [XRPLF/xrpl-dev-portal#1797]
Tutorial for creating a new AMM (using AMM-Devnet)

**Comment by intelliot** [comment]
Considering recent discussions about increasing usage of [XRPL-Standards](https://github.com/XRPLF/XRPL-Standards) and developers being confused about unavailable functionality being documented on XRPL.org:

In [XRPL-Standards](https://github.com/XRPLF/XRPL-Standards), consider creating a folder (`XLS-30d`) and putting the tutorial there. It should be a Markdown document. Then, add links to it from XRPL.org.

@Silkjaer @amarantha-k What do you think?

Personally, I have no problem with AMM tutorials and content on XRPL.org, but @Silkjaer seemed to have some concern about that.

**Comment by Silkjaer** [comment]
Sounds good to me. It's all up to you where to host this, XLS, own website or elsewhere. But until the amendment is merged into master it should not be on xrpl.org :)

**Comment by mDuo13** [comment]
This work has been moved to https://github.com/ripple/opensource.ripple.com/pull/11
