### ISSUE TITLE
Remove Federated Sidechains

### ISSUE THREAD

**Issue by oeggert** [XRPLF/xrpl-dev-portal#1834]
The [Federated Sidechains](https://xrpl.org/federated-sidechains.html) page is an outdated implementation of xls-38d. This page should be removed, since it's counterpart (and up-to-date documentation) exists on opensource.ripple.com

**Comment by amarantha-k** [comment]
The task has been completed. Content related to xls-38d (in development) is available on https://opensource.ripple.com/docs/xls-38d-cross-chain-bridge/cross-chain-bridges/
