### ISSUE TITLE
Update nft_info field documentation

### ISSUE THREAD

**Issue by godexsoft** [XRPLF/xrpl-dev-portal#1841]
The field documented as `nft_sequence` is now called `nft_serial`. This probably needs to be updated in the docs.

**Comment by ckniffen** [comment]
What version was this updated in?  The explorer references the old property still.

**Comment by godexsoft** [comment]
~It's not released yet but it's being changed in the next release of clio [from this pr](https://github.com/XRPLF/clio/pull/313/files#diff-42c04feb78d3b31663670d28c68ff999b5ef8585064b3a9f79a5bed24e992e1cR63). Not sure about rippled (cc @ledhed2222)~

Update: merged and released in clio 2.0-rc1

**Comment by ckniffen** [comment]
Rippled doesn't have nft_info so that wont be an issue.  I will make a PR today to support both fields and then we can remove support for the old one after release.

**Comment by godexsoft** [comment]
There are a few more other changes that i did not realise:
* `nft_sequence` is now `nft_serial`
* `uri` is no longer hex decoded
* `uri` is no longer `null` for the special case (as per the doc) but will be set to empty string instead.

All this is described in the pr i linked above.
Let's make sure docs and explorer are on the same page with the latest changes.
Please also keep in mind that none of this is actually deployed yet on any servers.

**Comment by mvadari** [comment]
Bumping this because I don't think it's been updated yet

**Comment by DennisDawson** [comment]
Changes merged in https://github.com/XRPLF/xrpl-dev-portal/pull/2455.

**Comment by amarantha-k** [comment]
Reopening as the examples in the Response Format are not updated and still show "nft_sequence" instead of "nft_serial".

**Comment by DennisDawson** [comment]
Fixed and merged.
