### ISSUE TITLE
'nft_info' rpc under Clio Server of the xrp ledger document can't be requested success.

### ISSUE THREAD

**Issue by qiangjiyi** [XRPLF/xrpl-dev-portal#1876]
I'm trying to request 'nft_info' api by postman. but response is error.

<img width="906" alt="image" src="https://user-images.githubusercontent.com/16377279/233294132-becefae6-9905-4176-bc64-abec4a5f55b3.png">

So how can i get the detail info about nft?

**Comment by ckniffen** [comment]
@qiangjiyi `nft_info` is a clio specific method so will need to to query a server running that.

**Comment by intelliot** [comment]
There are some public Clio servers, but if you have the ability, it would be best to run your own instance. [Learn more about the Clio server here](https://xrpl.org/the-clio-server.html). If you have any questions or issues, please ask here: https://github.com/XRPLF/clio/issues
