### ISSUE TITLE
Margins for breadcrumb list.

### ISSUE THREAD

**Issue by tequdev** [XRPLF/xrpl-dev-portal#1909]
I think there should be a margin on the left side of the breadcrumb list.

<img width="1018" alt="スクリーンショット 2023-05-17 19 58 42" src="https://github.com/XRPLF/xrpl-dev-portal/assets/69445828/9ce08d61-4bfe-44e7-beb6-82a299cdfa35">

**Comment by mDuo13** [comment]
This is specifically a problem with the references page template, but we probably won't fix it before switching to Redocly (where all these templates and spacing issues will be different)
