### ISSUE TITLE
Redirect /community to /contribute.html

### ISSUE THREAD

**Issue by mDuo13** [XRPLF/xrpl-dev-portal#1915]
Some Apex videos send people to https://xrpl.org/community which is a 404. We should add a redirect to send people to the right page, which is probably https://xrpl.org/contribute.html

Probably using the redirect template and using the filename filename `/community/index.html` with `redirect_url: contribute.html` should be enough.

**Comment by AnmolSirola** [comment]
@mDuo13 Can I work on this issue ?

**Comment by intelliot** [comment]
@AnmolSirola Yes.

**Comment by AnmolSirola** [comment]
@mDuo13 @intelliot I am not able to find the file where I need to make these changes. Can you guys help me with that ?

**Comment by mDuo13** [comment]
This task is no longer relevant since the new (Redocly-based) site uses `/community` as the canonical URL. (It also redirects from the legacy URL.)
