### ISSUE TITLE
Multiple explainer videos autoplay audibly in the background

### ISSUE THREAD

**Issue by mDuo13** [XRPLF/xrpl-dev-portal#1919]
In some cases, pages with explainer videos seem to automatically and audibly play multiple videos in the background. There's no visible indicator on the page (although you can see in browser that the tab is playing audio) but suddenly you're assaulted by something like crowd noise with many voices talking at the same time about explaining the XRP Ledger.

We found and fixed a version of this that happened on the new docs homepage design (#1866) when the user clicked some non-link text in boxes that had the `video-image` class applied while the page was loading. An ex-Rippler contacted me to report the same bug happening again in production a few days ago, so there must be additional triggers. There is probably some JavaScript code that is the root cause of the problem so we should look into that and hopefully figure out how to more thoroughly prevent this from happening.

The new variant is reported on Chrome. The previous bug was reproduced on both Firefox and Chrome.

**Comment by mDuo13** [comment]
The original issue triggered on https://xrpl.org/docs.html . 

No word yet on where the new instance occurred, but I'm guessing it could be on any page that has explainer videos embedded, such as https://xrpl.org/xrp-ledger-overview.html or https://xrpl.org/impact.html (less likely on the ones like Impact that have only one video)

**Comment by JST5000** [comment]
Closing for now until there are steps to reproduce - please re-open if we discover those :)

**Comment by mDuo13** [comment]
This happened again during the usability test, though there is not yet a confirmed way to repro, it has happened on multiple occasions to several different people so there should be a way, and it's bad enough when it happens that we should put some effort in fixing this.

**Comment by ckniffen** [comment]
Fix #2003

**Comment by JST5000** [comment]
Resolved with above PR
