### ISSUE TITLE
On XRPL Docs pages with multiple labels, the labels seem to be overlapping or missing sufficient padding.

### ISSUE THREAD

**Issue by amarantha-k** [XRPLF/xrpl-dev-portal#1927]
Here's an example page - https://xrpl.org/xrpl-quickstart.html. 
![image](https://github.com/XRPLF/xrpl-dev-portal/assets/13425257/33930aab-3b34-4464-b15e-29bf271273b0)

**Comment by mDuo13** [comment]
Labels have been retired from docs pages so this is no longer relevant.
