### ISSUE TITLE
Publish Quickstart updates in dactyl

### ISSUE THREAD

**Issue by DennisDawson** [XRPLF/xrpl-dev-portal#1930]
- Publish the Python tutorials
- Add Javascript and Python subheads under Quickstart
- Publish the source code in individual files
- Make short videos available as links, if not inline
- Continue to update docs in place until they can be transferred to Redocly
- Change all _NFToken_ references to _NFT_, except when talking about syntax

**Comment by mDuo13** [comment]
I think this is _mostly_ done by #1911 ?
