### ISSUE TITLE
New tutorials page issues

### ISSUE THREAD

**Issue by mDuo13** [XRPLF/xrpl-dev-portal#1938]
There seem to be some weird style things with the new tutorials landing page (added by #1896) that don't happen the same way on other landing pages.

## Cards are too narrow at many breakpoints. 

At some screen widths, the cards compress so small that they hardly fit any text at all and end up really tall and skinny. It's extra obvious the "SDKs" section because the fourth card is on its own line:

![2023-06-07_165718_127894706](https://github.com/XRPLF/xrpl-dev-portal/assets/7515597/5946d74c-2748-4cd3-98bb-7d2eaf41f928)

If you look at the homepage's cards they have breakpoints configured so they switch to a layout with fewer columns sooner to make sure this doesn't happen.

## Cards don't animate like they should

When the entire card is a link, it should animate by sliding upward a little when you hover over it. The tutorial cards don't do this. The problem is the wrapping div's class. If you use `card-deck` rather than `card-grid` you'll get the intended effect.

Currently:

```html
<div id="sdk-cards" class="card-grid card-grid-3xN tutorial-card-grid">
```

Suggestion:

```html
<div id="sdk-cards" class="row row-cols-1 row-cols-lg-3 card-deck mt-10 tutorial-card-grid">

```

## SDKs are treated as external links even though they shouldn't be

These links are local pages within the site, so they shouldn't be categorized as external, which causes them to have a diagonal arrow and to open in a new tab.

The solution is to remove `"external": true` from the data stanzas in the template file.

## Template filename doesn't match convention

The filename is `pagetype-tutorials.html.jinja` but the "pagetype-" prefix is supposed to be for templates that are reused across an entire _type_ of pages. This template is a one-off that can only be used for the "tutorials" page, so it should properly be named `page-tutorials.html.jinja`.

**Comment by pdp2121** [comment]
Hi @mDuo13 , I will work on a PR to fix these issues today
