### ISSUE TITLE
Remove old "New in: rippled X.Y.Z" badges

### ISSUE THREAD

**Issue by mDuo13** [XRPLF/xrpl-dev-portal#1978]
The badges indicating when a feature was added are extraneous and sometimes distracting information when they refer to really old versions. You can't keep synced with the blockchain unless you're running a recent version anyway, so these are only useful for a limited time unless people are updating _very outdated_ code or they're trying to do some sort of historical digging, in which case they should expect to rely on release notes anyway.

As a general policy, we should keep badges that are < ~2 years old (probably about 4-8 scheduled releases), which aligns with the timeline for retiring amendments (XLS-11d).

To avoid too many merge conflicts, this should be done on the `IA.v3` branch or on the master branch after merging that one. (It's started in some places already.) We should also update the contributing guidelines to add the above rule/guidance.

**Comment by intelliot** [comment]
In certain cases (changes of historical importance), perhaps the badge could be replaced with a footnote, which is less distracting than a colored badge.
