### ISSUE TITLE
Improve UI for readability in dark mode

### ISSUE THREAD

**Issue by amarantha-k** [XRPLF/xrpl-dev-portal#2001]
Tracking ticket to address feedback on poor contrast for code elements in paragraphs which affects readability. 
For example, see the "Description" of the `can_delete` parameter of the `can_delete` method in the screenshot: 
![image (1)](https://github.com/XRPLF/xrpl-dev-portal/assets/13425257/8404b788-377f-49b2-bfa3-a6542905bccc)

**Comment by bugsbunnies** [comment]
Code elements should follow this guide here (background is green100, text is green40) https://www.figma.com/file/BhSopy6K5jWIX8c93bnSEO/Docs-(Redocly)-Redesign?type=design&node-id=932%3A1143&mode=design&t=Yp45TvVuzQORaKom-1
Light mode is to the right of this screen 

Edited: Attached screenshots

<img width="1287" alt="image" src="https://github.com/XRPLF/xrpl-dev-portal/assets/39572746/a95c2bfe-b821-4c55-aa74-8d1a65536436">

<img width="1382" alt="image" src="https://github.com/XRPLF/xrpl-dev-portal/assets/39572746/ea1a7d1f-e966-4554-b84d-17566f476d18">

**Comment by AKCodez** [comment]
Proposed Solution: global styling for code snippets in markdown files: [PR](https://github.com/XRPLF/xrpl-dev-portal/pull/2009)

**Comment by AKCodez** [comment]
Solution has been merged, @amarantha-k we can now close this issue.

**Comment by amarantha-k** [comment]
Thanks @AKCodez! I've updated the status of the ticket to Done. Will close the issue once the fix has been deployed.
