### ISSUE TITLE
Collapse of code block

### ISSUE THREAD

**Issue by tequdev** [XRPLF/xrpl-dev-portal#2014]
Background color of text in Code block is broken when in light mode.

(Confirmed in Chrome and Safari)

<img width="723" alt="スクリーンショット 2023-07-20 16 12 56" src="https://github.com/XRPLF/xrpl-dev-portal/assets/69445828/76ff7f86-604e-402f-9fe7-96a4b43157b0">
<img width="704" alt="スクリーンショット 2023-07-20 16 13 06" src="https://github.com/XRPLF/xrpl-dev-portal/assets/69445828/c2ceff77-43ab-499c-8282-42e2d7f37e88">

**Comment by tequdev** [comment]
fixed by #2024

**Comment by mDuo13** [comment]
Just discovered this still applies when the code block is nested in a bulleted list, as in https://xrpl.org/configure-online-deletion.html

**Comment by mDuo13** [comment]
changing the selector from `.content ol code, .content ul code` to `.content li > code` should fix this
