### ISSUE TITLE
Remove mention of clio 1.1.0 from nft_info doc

### ISSUE THREAD

**Issue by godexsoft** [XRPLF/xrpl-dev-portal#2066]
[Here](https://github.com/XRPLF/xrpl-dev-portal/pull/1461/files) a pill claiming this is "new in clio 1.1.0" was added to https://xrpl.org/nft_info.html.

Please change to version 1.0.4 👍

**Comment by DennisDawson** [comment]
Addressed by https://github.com/XRPLF/xrpl-dev-portal/pull/2498.

**Comment by DennisDawson** [comment]
Actually, ended up changing the release to 2.0.0, which was the correct release. Amarantha caught this, my bad.
