### ISSUE TITLE
Document QualityIn & QualityOut fields

### ISSUE THREAD

**Issue by matejr** [XRPLF/xrpl-dev-portal#208]
Description of QualityIn and QualityOut fields is very short and vague ("Value(?) incoming balances"):

https://developers.ripple.com/trustset.html

This page

https://web.archive.org/web/20150422102043/https://wiki.ripple.com/Trust_line_quality

contains an explanation but it is deprecated.

_(I edited the Trust Line Quality link to use the wayback machine instead of the broken wiki. --@mduo13)_

_(I edited the TrustSet link to point directly to the doc page on developers.ripple.com. The old ripple.com/build link redirected to the Transaction Formats hub page. -- @jhaaaa)_

**Comment by mDuo13** [comment]
Yep, this is on the backlog. Has been for a while, because Trust Line Quality is not a much-used feature...

**Comment by christopheroye** [comment]
Current: Create or modify a trust line linking two accounts. -- Is this information deprecated?

If so, who are Trust Set for and how are they being used today?

**Comment by yxxyun** [comment]
> Current: Create or modify a trust line linking two accounts. -- Is this information deprecated?
> 
> If so, who are Trust Set for and how are they being used today?

https://xrpl.org/issued-currencies.html

**Comment by christopheroye** [comment]
submitted a Pull Request [Update Trust.md](https://github.com/ripple/xrpl-dev-portal/pull/729)

**Comment by q411** [comment]
https://github.com/ripple/xrpl-dev-portal/pull/777

**Comment by q411** [comment]
https://github.com/ripple/xrpl-dev-portal/pull/777

**Comment by DennisDawson** [comment]
Fixed in https://github.com/XRPLF/xrpl-dev-portal/compare/issue_208.
