### ISSUE TITLE
Broken icons to external links in FAQ page.

### ISSUE THREAD

**Issue by tequdev** [XRPLF/xrpl-dev-portal#2085]
Arrows Icons are shown too far up.

<img width="1119" alt="スクリーンショット 2023-08-23 22 55 14" src="https://github.com/XRPLF/xrpl-dev-portal/assets/69445828/48c43b5f-96ee-421c-8187-3c31c413c39f">

**Comment by DESMOND555** [comment]
Hello  this is Desmond Kingsley, please I call for the assistance of to
respond to me please, I've been under some challenges for over 2 months now
please I plead to you to write to me on WhatsApp +2349136843896

**Comment by mDuo13** [comment]
Assigned to @AKCodez because I suspect this was caused by #1925.

**Comment by AKCodez** [comment]
Can anyone else replicate this? I cant seem to replicate it.

**Comment by mDuo13** [comment]
This is no longer an issue on the current version of the site.
