### ISSUE TITLE
Send Currency not working

### ISSUE THREAD

**Issue by margin-hub** [XRPLF/xrpl-dev-portal#2092]
I tried to execute this sample tutorial([Create Trust Line and Send Currency](https://xrpl.org/create-trustline-send-currency.html)) and this often failed, not sure where's the issue.
What i did was:
1. Create Trustline first.
2. Enter the currency, input amount, dest address and click `SendCurrency` button.
I've attached my screenshot and hope this will be helpful in understanding the situation for you.

Keen to hear any update from you, thanks!

![Monosnap Token Test Harness 2023-08-29 19-41-02](https://github.com/XRPLF/xrpl-dev-portal/assets/58267901/d43ba1f3-7aa9-4294-9153-d37b12648416)

**Comment by mDuo13** [comment]
It's not clear from the screenshot what the cause of the problem is. If you are on PC you can press F12 to open the developer console and see if there's a more descriptive error message.

P.S. if you're going to blur out the seeds for privacy, you should also blur out the private keys.

**Comment by margin-hub** [comment]
Thanks for your information, i caught it and it's related to not setting the trustline between them.
Oh my bad, i didn't blur out private keys, haha!

**Comment by DennisDawson** [comment]
Looking at the example, the code is actually confusing. I need to revise the sample and add more explanation, based on my improved understanding now versus when I first wrote the example. Thank you for pointing out the problem!

**Comment by DennisDawson** [comment]
Done.
