### ISSUE TITLE
The height of the left sidebar has changed

### ISSUE THREAD

**Issue by tequdev** [XRPLF/xrpl-dev-portal#2150]
`Documentation` is hidden in top-nav.

https://xrpl.org/introduction.html
<img width="1893" alt="スクリーンショット 2023-09-22 2 35 53" src="https://github.com/XRPLF/xrpl-dev-portal/assets/69445828/13fca9e7-2e06-4a9e-891e-ed095eeff3ef">
<img width="623" alt="スクリーンショット 2023-09-22 2 37 33" src="https://github.com/XRPLF/xrpl-dev-portal/assets/69445828/25d53cca-6f15-4609-86dd-28997ad5a04f">

https://xrpl.org/what-is-the-xrp-ledger.html
<img width="1759" alt="スクリーンショット 2023-09-22 2 36 19" src="https://github.com/XRPLF/xrpl-dev-portal/assets/69445828/5e2717fa-4fd7-468f-8cec-5c92e56ebee1">
<img width="839" alt="スクリーンショット 2023-09-22 2 37 59" src="https://github.com/XRPLF/xrpl-dev-portal/assets/69445828/7b0ace62-9997-4188-b72b-c4f4c105170c">

**Comment by tequdev** [comment]
https://xrpl.org/docs-index.html

We can't see "See Everything" at top.
<img width="704" alt="スクリーンショット 2023-09-27 1 37 21" src="https://github.com/XRPLF/xrpl-dev-portal/assets/69445828/122f6d74-9b1e-4e43-be4d-ee0f9f3c97c6">

**Comment by mDuo13** [comment]
We won't be fixing this on the current (Dactyl-based) templates, but this should hopefully resolve itself as part of the move to Redocly.
