### ISSUE TITLE
Migrate pages under About to Redocly

### ISSUE THREAD

**Issue by amarantha-k** [XRPLF/xrpl-dev-portal#2192]
The following pages are currently built using a combination of HTML, CSS, and Jinja templates. 
These need to be migrated to React pages to be included in the Redocly build. 
- [x] https://xrpl.org/
- [x] https://xrpl.org/xrp-ledger-overview.html
- [x] https://xrpl.org/history.html
- [x] https://xrpl.org/xrp-overview.html
- [x] https://xrpl.org/impact.html
- [x] https://xrpl.org/carbon-calculator.html
- [x] https://xrpl.org/faq.html
- [x] https://xrpl.org/contribute.html
- [x] https://xrpl.org/events.html
- [x] https://xrpl.org/ambassadors.html
- [x] https://xrpl.org/privacy-policy.html
- [x] https://xrpl.org/developer-funding.html
- [x] https://xrpl.org/dev-tools.html
- [x] https://xrpl.org/docs.html
- [ ] https://xrpl.org/code-samples.html
- [ ] https://xrpl.org/uses.html

Note: There was some work done earlier this year to migrate some of these pages and we may be able to update them. 
However, in some cases, pages have been revamped since the last migration effort and it may be better/easier to start afresh.

**Comment by AKCodez** [comment]
having trouble integrating bodymovin animation on impact page, everything else for impact completed, will be checking off items as I have pushed them to my branch   ak-convert-jinja-tsx

**Comment by AKCodez** [comment]
Waiting for ecosystem PR to be merged in order to do uses.html page.

**Comment by AKCodez** [comment]
Checking off carbon-calculator as it is redirecting to impact on xrpl.org already

**Comment by AKCodez** [comment]
Contribute needs typeform integration and animations

**Comment by AKCodez** [comment]
Added dev tools page, but all those pages still need the sidebar integrated into the layout, dont know who is responsible for handling that.

**Comment by AKCodez** [comment]
Summary, pages that still need work.

- Impact: needs bodymovin animations

- uses: waiting on merge of new uses page to then convert over to react.

- contribute: needs bodymovin animation

- dev-tools: needs sidebar in layout.

- code-samples: need to convert python script to get all code sample pages in react.

**Comment by AKCodez** [comment]
Impact page animations added

**Comment by AKCodez** [comment]
Contribute animations added

**Comment by amarantha-k** [comment]
Roman mentioned that he'll be looking into the sidebar issue and adding a hook for route navigation (for interactive guides) this week.

**Comment by mDuo13** [comment]
This is done now (although code samples is currently broken, that's separate)
