### ISSUE TITLE
Migrate Dev Tools to Redocly

### ISSUE THREAD

**Issue by amarantha-k** [XRPLF/xrpl-dev-portal#2194]
The following pages are currently built using a combination of HTML, CSS, and Jinja templates.
These need to be migrated to React pages to be included in the Redocly build.
- [x] RPC Tool 
- [x] WebSocket API Tool
- [x] xrp-ledger.toml Checker 
- [x] XRP Faucets
- [x] Transaction Sender 
- [ ] Domain Verification Checker

Note: There was some work done earlier this year to migrate some of these pages and we may be able to update them.
However, in some cases, pages have been revamped since the last migration effort and it may be better/easier to start afresh.

**Comment by mDuo13** [comment]
This is done now
