### ISSUE TITLE
Migrate xrpl.org/blog to Redocly

### ISSUE THREAD

**Issue by amarantha-k** [XRPLF/xrpl-dev-portal#2195]
Migrate https://xrpl.org/blog/ to the Redocly Developer Portal.

**Comment by amarantha-k** [comment]
As part of this issue, the dev-blog content will be moved from the `ripple/dev-blog` repository to `XRPLF/xrpl-dev-portal` repository.

**Comment by mDuo13** [comment]
Fixed in #2346 (except for landing pages / homepage).

**Comment by mDuo13** [comment]
Created #2360 to track the follow-up work
