### ISSUE TITLE
Verify System Requirements (and update them if necessary)

### ISSUE THREAD

**Issue by intelliot** [XRPLF/xrpl-dev-portal#2204]
https://xrpl.org/system-requirements.html

Community members would like to know if infrastructure should be upgraded "to be on the safe side". Are there any updates that can/should be made to the documented System Requirements?

There is a perception that the Minimum Specifications may be unrealistically low. The page should emphasize that the minimum is not for production.

**Comment by mDuo13** [comment]
Fixed in #2219
