### ISSUE TITLE
Overlapping of elements 

### ISSUE THREAD

**Issue by AnuragNishad12** [XRPLF/xrpl-dev-portal#2240]
<img width="950" alt="image" src="https://github.com/XRPLF/xrpl-dev-portal/assets/124987038/20ba4f67-c4ca-4f2f-b659-717be94d8130">

**Comment by mDuo13** [comment]
The labels are going to go away entirely in the next version of the site (in the next couple months), so we won't be fixing this in the current version of the site.

**Comment by AnuragNishad12** [comment]
okay  and we should add a section about how to create application on react.js using XRPL with its data

**Comment by intelliot** [comment]
@AnuragNishad12 can you open a new issue for that (if you haven't yet)?
