### ISSUE TITLE
Re-create blog landing pages in Redocly

### ISSUE THREAD

**Issue by mDuo13** [XRPLF/xrpl-dev-portal#2360]
Landing pages, including the blog homepage and category landings (for example https://xrpl.org/blog/label/developer-reflections.html ) need to be re-created in Redocly. Possibly this can be done with a Redocly plugin such as the one we use for index pages (`@theme/plugins/index-pages.js`)

**Comment by amarantha-k** [comment]
The revised Blog landing page has been implemented in PR#2388.
