### ISSUE TITLE
Tutorials page naming confusion

### ISSUE THREAD

**Issue by mDuo13** [XRPLF/xrpl-dev-portal#2460]
In the left sidebar, the page is listed as "Crypto Wallet and Blockchain Development Tutorials" which is very long and doesn't match with the other category titles.

![2024-03-14_145228_151276592](https://github.com/XRPLF/xrpl-dev-portal/assets/7515597/aaa4da34-defc-4230-85a2-3cda156f88df)

In the center column, the page uses the same name in the breadcrumbs but the h1 just says "Tutorials".

**Comment by amarantha-k** [comment]
This has been fixed.
