### ISSUE TITLE
Bring back "Edit Page" button

### ISSUE THREAD

**Issue by mDuo13** [XRPLF/xrpl-dev-portal#2473]
The "Edit Page" button should appear somewhere on docs pages (likely the right sidebar or the top nav) and take you to a GitHub page where you can see the source file for the current documentation page, open an editor, and propose changes.

There might be a Redocly setting to turn this on, or a component that can be imported and added to our custom templates.

**Comment by amarantha-k** [comment]
This has been fixed.
