### ISSUE TITLE
Missing "optional" for CancelAfter field in PaymentChannelCreate

### ISSUE THREAD

**Issue by donovanhide** [XRPLF/xrpl-dev-portal#253]
See tx `C26C0FD55DC0EAED8EF1193C5BED8B83D603D71C804B2999E18A3CED9F91E91D` for example.

**Comment by mDuo13** [comment]
[Fixed](https://github.com/ripple/ripple-dev-portal/commit/d585c3f3d4a71d416e282af3a8f7050988a7b75c) and [Deployed](https://ripple.com/build/transactions/#paymentchannelcreate).
