### ISSUE TITLE
funded account, sending account what difference?

### ISSUE THREAD

**Issue by Relect** [XRPLF/xrpl-dev-portal#2531]
https://github.com/XRPLF/xrpl-dev-portal/blob/4200ea677119e6c2c051c91b1c8350f88b6d403c/docs/references/protocol/transactions/types/accountdelete.md?plain=1#L38

_Must be a funded account in the ledger, and must not be the sending account._
what difference?
The account is either on the ledger or it is not.
no differences are indicated when creating an account.

What is this a special account to which you can withdraw funds when you delete another account?

**Comment by mDuo13** [comment]
No, it's saying that when you delete an account and send out the leftover XRP:

- You can't use AccountDelete to create a new account (only Payment transactions can send to an address that isn't already funded)
- The sender of the AccountDelete transaction (that is, the account that's being deleted) can't send the funds to itself
