### ISSUE TITLE
bug: CSS issues - can't click on link

### ISSUE THREAD

**Issue by mvadari** [XRPLF/xrpl-dev-portal#2534]
I'm on this page: https://xrpl.org/docs/infrastructure/installation/install-clio-on-ubuntu/

I am unable to click on the `Clio source code repository` link due to what appears to be a CSS issue where when I hover over that paragraph, the hover of the title below it is activated instead.

**Comment by mvadari** [comment]
The same issue is apparent at https://xrpl.org/docs/references/http-websocket-apis/public-api-methods/server-info-methods/server_definitions

With the `Definitions File` link near the bottom.

Both times I had to inspect element in order to actually navigate to the link.

**Comment by amarantha-k** [comment]
This issue was also noted in #2520 and is fixed by #2539
