### ISSUE TITLE
Add Ripple Devnet/Testnet Clio endpoints to Public Servers List

### ISSUE THREAD

**Issue by kennyzlei** [XRPLF/xrpl-dev-portal#2537]
Currently, https://github.com/XRPLF/xrpl-dev-portal/blob/master/docs/tutorials/public-servers.md contains Ripple's rippled endpoints for Devnet and Testnet environments.  To provide visibility of the Clio servers, it would be valuable to also include the following URLs for Clio endpoints, in case developers are interested in testing [Clio-specific APIs](https://xrpl.org/docs/references/http-websocket-apis/public-api-methods/clio-server/) or have an endpoint that is more representable of Ripple's Mainnet setup which 100% of traffic is served by Clio servers.  There is value in having both existing endpoints and the currently non-published endpoints for developers to be aware of so they options in their testing

| Operator  | Network | JSON-RPC URL | WebSocket URL |
|:----------|:------------|:-------------|:--------------|
| Ripple   | Testnet     | `https://clio.altnet.rippletest.net:51234/` | `wss://clio.altnet.rippletest.net:51233/` |
| Ripple   | Devnet      | `https://clio.devnet.rippletest.net:51234/` | `wss://clio.devnet.rippletest.net:51233/` |

It would also be valuable to list these in the connections to try API requests: https://github.com/XRPLF/xrpl-dev-portal/blob/master/resources/dev-tools/components/websocket-api/data/connections.json

Similar to the existing Ripple public servers, these newly published endpoints should also have the footnote that they are not for sustained or business use.

**Comment by DennisDawson** [comment]
Changes merged
