### ISSUE TITLE
Missing SourceTag and DestinationTag in PayChannel ledger format description

### ISSUE THREAD

**Issue by donovanhide** [XRPLF/xrpl-dev-portal#254]
See https://github.com/ripple/rippled/blob/112a863e7346793234c973e97818ced4c6e36867/src/ripple/app/tx/impl/PayChan.cpp#L235-L236

**Comment by mDuo13** [comment]
Good catch. Not sure how that slipped through review, but I'll fix ASAP

**Comment by mDuo13** [comment]
[Fixed](https://github.com/ripple/ripple-dev-portal/commit/3b5d933c0cf60753465a302dfb48612d4fece5a2) and [deployed](https://ripple.com/build/ledger-format/#paychannel).
