### ISSUE TITLE
`terNO_LINE` and `terNO_RIPPLE` show incorrect explanations

### ISSUE THREAD

**Issue by mvadari** [XRPLF/xrpl-dev-portal#2546]
Page: https://xrpl.org/docs/references/protocol/transactions/transaction-results/ter-codes/#ter-codes

Both `terNO_LINE` and `terNO_RIPPLE` have this explanation:
```
Used internally only. This code should never be returned.
```
This is an incorrect explanation.

**Comment by mDuo13** [comment]
I believe that the `tec` versions of these codes is normal but the `ter` version is not normally returned. A [search of the rippled source](https://github.com/search?q=repo%3AXRPLF%2Frippled%20terNO_LINE&type=code) implies this might be correct, but the total code path is unclear.

**Comment by mvadari** [comment]
I appear to have incorrectly extrapolated from one to the other - that does seem to be true for `terNO_LINE`, but not `terNO_RIPPLE`, which does seem to have legitimate code paths.
Search link: https://github.com/search?q=repo%3AXRPLF%2Frippled+terNO_RIPPLE&type=code
