### ISSUE TITLE
Amendment ledger entry not documented

### ISSUE THREAD

**Issue by donovanhide** [XRPLF/xrpl-dev-portal#255]
See https://github.com/ripple/rippled/blob/35fa20a110e3d43ffc1e9e664fc9017b6f2747ae/src/ripple/app/tx/impl/Change.cpp#L106-L203

**Comment by mDuo13** [comment]
Yep, this has been on my backlog for a while

**Comment by mDuo13** [comment]
https://github.com/ripple/ripple-dev-portal/pull/279 fixes this

**Comment by mDuo13** [comment]
(Also docs are upcoming for the other two undocumented ledger object types, FeeSettings and LedgerHashes)
