### ISSUE TITLE
Unable to access the Footer link in docs page

### ISSUE THREAD

**Issue by tequdev** [XRPLF/xrpl-dev-portal#2555]
https://xrpl.org/docs/

Each link in the footer does not work.
I think the transparent element is up there.

<img width="1479" alt="スクリーンショット 2024-04-19 20 02 14" src="https://github.com/XRPLF/xrpl-dev-portal/assets/69445828/246fd08c-09be-4faa-93f6-95232fb169e2">

**Comment by mDuo13** [comment]
I haven't been able to figure out what's going on here yet but it's definitely a problem.
