### ISSUE TITLE
Localized page doesn’t ignored `markdown.partialsFolders`

### ISSUE THREAD

**Issue by tequdev** [XRPLF/xrpl-dev-portal#2574]
https://xrpl.org/ja/docs/_snippets/no-cli-syntax/

**Comment by mDuo13** [comment]
Acknowledged and reported upstream to Redocly

**Comment by mDuo13** [comment]
Supposed to be fixed in Realm v87.0

**Comment by tequdev** [comment]
It seems to have been fixed.
