### ISSUE TITLE
EscrowCreate doc missing error cases

### ISSUE THREAD

**Issue by DennisDawson** [XRPLF/xrpl-dev-portal#2677]
From Siva Kumar:
https://xrpl.org/docs/references/protocol/transactions/types/escrowcreate/ this page does not show potential errors that may occur. 

for example, https://xrpl.org/docs/references/protocol/transactions/types/nftokencreateoffer/#error-cases  NFTokenCreateOffer has error cases...whereas the EscrowCreate, EscrowFinish and EscrowCancel pages do not show any error handling details.

**Comment by ukd-skn** [comment]
@DennisDawson Thanks Dennis.

**Comment by mDuo13** [comment]
For the larger scope of the same issue, see #2666

**Comment by mDuo13** [comment]
(Closing this one as a duplicate)
