### ISSUE TITLE
[Nit] Payment transaction docs: IssuedCurrencies in lower case

### ISSUE THREAD

**Issue by ckeshava** [XRPLF/xrpl-dev-portal#2772]
The documentation asks that Issued Currencies be specified in lower-case in the `Amount`, `DeliverMax` and the `DeliverMin` fields.
> For non-XRP amounts, the nested field names are lower-case.

<img width="943" alt="image" src="https://github.com/user-attachments/assets/0a5828b3-1375-4790-b504-e49f9284f5a8">

This does not appear to be true in practice. The responses of `tx` command pertaining to Payment transactions return upper-case Issued Currency representations: https://xrpl.org/resources/dev-tools/websocket-api-tool?server=wss%3A%2F%2Fxrplcluster.com%2F&req=%7B%22id%22%3A%22example_Payment%22%2C%22command%22%3A%22tx%22%2C%22transaction%22%3A%227BF105CFE4EFE78ADB63FE4E03A851440551FE189FD4B51CAAD9279C9F534F0E%22%2C%22binary%22%3Afalse%7D

I suspect we can submit upper-case IssuedCurrency representations in Payment transaction inputs too (I haven't been able to check it yet). Is the above statement true today?

**Comment by mDuo13** [comment]
This seems to be a misunderstanding.

The field _names_ —specifically `currency`, `issuer`, and `value`—need to be lowercase. The field _values_ don't need to be.
