### ISSUE TITLE
Add server_definitions API method docs

### ISSUE THREAD

**Issue by mDuo13** [XRPLF/xrpl-dev-portal#2846]
Documents #4703

This new API method was added a couple versions back and isn't currently documented on the [Public Methods page](https://xrpl.org/docs/references/http-websocket-apis/public-api-methods)

**Comment by mvadari** [comment]
The page already exists: https://xrpl.org/docs/references/http-websocket-apis/public-api-methods/server-info-methods/server_definitions

**Comment by oeggert** [comment]
Closing this issue, since docs already exist.
