### ISSUE TITLE
Dead links

### ISSUE THREAD

**Issue by Silkjaer** [XRPLF/xrpl-dev-portal#2852]
community/report-a-scam.md should be updated to reflect that there is no xrpchat.com, xrplorer.com and XRP Forensics.

Thanks.

**Comment by amarantha-k** [comment]
Thanks for the ticket, @Silkjaer. I'll update the page.

**Comment by Silkjaer** [comment]
https://github.com/XRPLF/xrpl-dev-portal/pull/2874

**Comment by amarantha-k** [comment]
Addressed by https://github.com/XRPLF/xrpl-dev-portal/pull/2874
