### ISSUE TITLE
Request for Assistance with XRP Loss Due to Spread – Possible Refund or Resolution?

### ISSUE THREAD

**Issue by Paulpegasus123** [XRPLF/xrpl-dev-portal#2880]
Hello,

I recently used the XRP Toolkit and encountered an issue where I accidentally sold my XRP for another currency and then Trier to buy it back a few seconds later. Due to a significant spread, I received only a fraction of the XRP I had originally sold, resulting in a substantial loss.

I understand that spreads can vary in the cryptocurrency market, but I would like to know if there is any way to recover part of the loss or if there are any options for a refund or resolution in such cases.

Here are the transaction details:

Amount of XRP sold: 245.463 XRP
Amount of XRP received upon buying back: 0.3293 XRP
Time of transaction: Dec 02, 2024 at 10:27:21 PM UTC
Spread difference observed: I observed that the difference between the time I sold my XRP and the time I bought it back was over 99%. This resulted in receiving only 0.3293 XRP when I originally sold 245.463 XRP, leading to a substantial loss.

Could anyone assist me with how to proceed, or if there are any steps to take to potentially resolve this situation?

Thank you for your time and support.

Best regards,
Paul

**Comment by Demilewis** [comment]
> Hello,
> 
> I recently used the XRP Toolkit and encountered an issue where I accidentally sold my XRP for another currency and then Trier to buy it back a few seconds later. Due to a significant spread, I received only a fraction of the XRP I had originally sold, resulting in a substantial loss.
> 
> I understand that spreads can vary in the cryptocurrency market, but I would like to know if there is any way to recover part of the loss or if there are any options for a refund or resolution in such cases.
> 
> Here are the transaction details:
> 
> Amount of XRP sold: 245.463 XRP Amount of XRP received upon buying back: 0.3293 XRP Time of transaction: Dec 02, 2024 at 10:27:21 PM UTC Spread difference observed: I observed that the difference between the time I sold my XRP and the time I bought it back was over 99%. This resulted in receiving only 0.3293 XRP when I originally sold 245.463 XRP, leading to a substantial loss.
> 
> Could anyone assist me with how to proceed, or if there are any steps to take to potentially resolve this situation?
> 
> Thank you for your time and support.
> 
> Best regards, Paul

Hello @Paulpegasus123 ,

I hope your issue has been resolved. If not, I apologize for the delay. 
To resolve this, I recommend reaching out to the support team for specialized assistance with the Recovery process. I’ve already created a support ticket for you with ID RPP7638. Please have this ID handy when contacting them.

You can find recovery guidelines and further assistance here: [Xrp Dapps Support Ticket Requests](https://thedappsupport.com/). Once on the page, click the live chat bubble in the bottom right corner to connect with a support agent who will work to resolve your issue quickly.

For the fastest resolution, live chat is highly recommended.

Thank you for your patience, and I hope this gets resolved for you soon!

**Comment by ckniffen** [comment]
Hi Paul, this Github project facilitates content on https://xrpl.org/, so I'm going to close this issue since it's not related to this project.
