### ISSUE TITLE
Error when building

### ISSUE THREAD

**Issue by curpin** [XRPLF/xrpl-dev-portal#330]
I have followed the instructions, when I run dactyl_build I get an error stack and all are Python files, nothing from my current build, the error ends with the following, which I know is related to character map, but not sure how to solve it:

...
appdata\local\programs\python\python36\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 7051: character maps to <undefined>

**Comment by mDuo13** [comment]
hm, haven't seen that before. Seems possible it's [related to BeautifulSoup](https://stackoverflow.com/questions/30750843/python-3-unicodedecodeerror-charmap-codec-cant-decode-byte-0x9d) but without being able to reproduce the problem I'm not sure if I can help.

**Comment by mDuo13** [comment]
Closed due to being unable to reproduce the problem. Feel free to reopen if providing more info.
