### ISSUE TITLE
Public API: JSON-RPC and Commandline Output formats missing for some methods

### ISSUE THREAD

**Issue by mikemilano** [XRPLF/xrpl-dev-portal#407]
Nothing critical here, but in case it has been missed... I am seeing pages which show request formats for `JSON-RPC` and `Commandline`, but are missing output formats.

Without running them, it's unclear whether there is anything different about running these and the websocket implementation, or if the docs are simply incomplete. (Of course I can run them, but just communicating the first impression of someone consuming the docs)

I went through the first 3 sections. These all have `Websocket` outputs defined, but are missing either `JSON-RPC`, `Commandline`, or both for output formats.

Account
- https://developers.ripple.com/account_info.html
- https://developers.ripple.com/account_objects.html
- https://developers.ripple.com/account_offers.html
- https://developers.ripple.com/account_tx.html

Ledger
- https://developers.ripple.com/ledger.html
- https://developers.ripple.com/ledger_closed.html
- https://developers.ripple.com/ledger_current.html
- https://developers.ripple.com/tx.html
- https://developers.ripple.com/ledger_entry.html

Transactions
- https://developers.ripple.com/submit_multisigned.html
- https://developers.ripple.com/transaction_entry.html
- https://developers.ripple.com/tx.html
- https://developers.ripple.com/tx_history.html

**Comment by mDuo13** [comment]
These are probably just incomplete/missing examples. (I ran all the examples by hand and didn't always have a convenient, illustrative example in all three formats.)

Will try to fix this as I come across them.

**Comment by mDuo13** [comment]
Note to self: add JSON-RPC formats for the [Checks tutorials](https://developers.ripple.com/send-a-check.html) too

**Comment by mDuo13** [comment]
Mostly fixed by #871. The Checks tutorials still don't have JSON-RPC examples and [submit_multisigned](https://xrpl.org/submit_multisigned.html) is missing the Commandline response format

**Comment by q411** [comment]
https://xrpl.org/submit_multisigned.html

**Comment by q411** [comment]
https://xrpl.org/submit_multisigned.html

**Comment by amarantha-k** [comment]
There is a separate ticket to update Checks tutorials (#1206). So just need to address the missing example response for [submit_multisigned](https://xrpl.org/submit_multisigned.html).
