### ISSUE TITLE
sign_for request parameter restrictions missing?

### ISSUE THREAD

**Issue by mikemilano** [XRPLF/xrpl-dev-portal#415]
The `sign` method has the following parameter restrictions, however they are not documented in `sign_for`, which uses the same parameters.

I didn't want to open a PR because I wasn't sure if it was intentional, or missed.

- `secret` cannot be used with `key_type`, `seed`, `seed_hex`, `passphrase`
- `seed` must also have `key_type` and cannot be used with `secret`, `seed_hex`, `passphrase`
- `seed_hex` must also have `key_type` and cannot be used with `secret`, `seed`, `passphrase`
- `passphrase` must also have `key_type` and cannot be used with `secret`, `seed`, `seed_hex`
- `key_type` cannot be used with `secret`

**Comment by mDuo13** [comment]
I believe it should be the same. In fact, I think they use some shared code to enforce those rules.

Will double-check and update as appropriate.
