### ISSUE TITLE
XRP and drop naming is not explained

### ISSUE THREAD

**Issue by MarkusTeufelberger** [XRPLF/xrpl-dev-portal#419]
XRP as a name is often used, but on https://developers.ripple.com/xrp.html the explanation what XRP actually stands for (an ISO 4217 compatible code for "Ripple credits/ripples", "1 XRP is one ripple") as well as the inventor of the "drop" name (ThePiachu in https://forum.ripple.com/viewtopic.php?f=1&t=40&p=228 - they might have even been called "Jeds" otherwise) is missing.

**Comment by yxxyun** [comment]
I think this is for reasons,  name XRP "ripples" maybe confused people and made them think it was a securities.

**Comment by MarkusTeufelberger** [comment]
I wouldn't think that I'm buying Amazon shares with Amazon Coins or Google shares if I'm buying something called "googles". I also don't see any reason why naming something like the concept it enables makes it a security. After all, Ripple Labs was called "Open Coin" back when XRP/ripples/Ripple credits were named/invented.
