### ISSUE TITLE
Native Debian / Ubuntu package required  -   yum-utils nonexistent and unsupported

### ISSUE THREAD

**Issue by rafael5** [XRPLF/xrpl-dev-portal#473]
Since the most prevalent cloud server now is  Debian/Ubuntu  (see links below), and the latest packages appear on Debian/Ubuntu  (which developers need) could you please provide a native Debian installation under apt-get?

Note:  I tried to install the yum-utils for the Debian version but ___yum-utils does not exist on the apt-get repository___.   I tried also downloading the yum-utils.deb package directly, but it does not have any  ./config or installation instructions.

W3TECHS - https://w3techs.com/technologies/details/os-linux/all/all
Ubuntu - 34.1%
Debian - 31.4%
CentOS - 20.6%
Red Hat - 3.7%
Gentoo - 2.7%

W3COOK - http://www.w3cook.com/os/ubuntu
Ubuntu - 29.9%
CentOS - 24.57%
Debian - 11.31%
Fedora - 0.68%
Red Hat - 0.01%

THE CLOUD MARKET - http://thecloudmarket.com/stats
Ubuntu - 57.5%
Windows - 7.8%
Red Hat - 4.8%
CentOS - 3.7%
Fedora 1.4%

OPENSTACK - http://www.openstack.org/assets/survey/April-2016-User-Survey-Report.pdf (Page 47)
Ubuntu - 55% (With an potential growth of up to 19%)
CentOS - 20% (With an potential growth of up to 7%)
Red Hat - 16% (With an potential growth of up to 4%)
SUSE - 2% (With an potential growth of up to 1%)
Debian - 3% (With an potential growth of up to 0%)

**Comment by mDuo13** [comment]
Can you re-open this issue at https://github.com/ripple/rippled/issues ? This project is only for the documentation, but creating a native Debian/Ubuntu package would require the work of a release/packaging engineer. (Not something I'm an expert on.)

**Comment by mDuo13** [comment]
Oh, but if you can specify which version of Ubuntu doesn't have yum-utils, I can update the documentation to clarify that part.

**Comment by mDuo13** [comment]
Nevermind: I see it's already happened ( https://github.com/ripple/rippled/issues/2756 )
