### ISSUE TITLE
Accounts created via test faucet not being available in the test network

### ISSUE THREAD

**Issue by tit4** [XRPLF/xrpl-dev-portal#520]
HI,

Im creating a test account using [test faucet](https://developers.ripple.com/xrp-test-net-faucet.html).

`curl -s -X POST https://faucet.altnet.rippletest.net/accounts`
```
{"account":{"secret":"shgwzzmyf5QHhTnrnFNK62YfPapkx","address":"rhHjQnUsKDHxi5M15a56gryus7YYJUqn1p"},"balance":10000}
```

but when Im trying to get the account information using the test network (https://s.altnet.rippletest.net:51234) Im getting "account not found error"

**Comment by mDuo13** [comment]
I can't reproduce this problem, and the [interactive XRP-sending tutorial](https://developers.ripple.com/send-xrp.html) seems to work without having this problem, either.

I'm not sure if you encountered a service blip, or if you're trying to get the account information before the transaction creating it has been confirmed, or if you're doing something else wrong, but this doesn't seem to be an ongoing problem.

This also isn't quite the right repo for this sort of problem (this is just for the docs, not the faucet) but if you can provide more info on how to reproduce, I can pass it on to the people who would be able to fix it.

**Comment by gazoscalvertos** [comment]
I can also confirm I am experiencing this issue.

The interactive XRP-sending tutorial is also not behaving as expected. I've generated the keypair, connected to the testnet then when trying to prepare transaction the following appears in the web console:

Uncaught (in promise) RippleError: actNotFound
    at t.default.<anonymous> (https://developers.ripple.com/assets/js/ripple-lib-1.1.2-min.js:15:480505)
    at t.default.i (https://developers.ripple.com/assets/js/ripple-lib-1.1.2-min.js:15:128033)
    at t.default.n.emit (https://developers.ripple.com/assets/js/ripple-lib-1.1.2-min.js:15:126849)
    at t.default._onMessage (https://developers.ripple.com/assets/js/ripple-lib-1.1.2-min.js:15:475415)
    at i.n.emit (https://developers.ripple.com/assets/js/ripple-lib-1.1.2-min.js:15:126849)
    at WebSocket._ws.onmessage (https://developers.ripple.com/assets/js/ripple-lib-1.1.2-min.js:15:483538)

Is there a time delay?

**Comment by gazoscalvertos** [comment]
[Cross posted here](https://github.com/ripple/testnet-faucet/issues/1)

**Comment by mDuo13** [comment]
There should not be a time delay. It's possible the faucet is malfunctioning.
