### ISSUE TITLE
Validator configuration using public hubs

### ISSUE THREAD

**Issue by alloynetworks** [XRPLF/xrpl-dev-portal#540]
The instructions in this document (https://developers.ripple.com/run-rippled-as-a-validator.html#connect-using-public-hubs) can leave a validator without connectivity. The public hubs are meant for bootstrapping, and **not** for `[ips_fixed]` in conjuction with `[peer_private]` as 1.

If, for any reason, the hubs are unable to provide a slot to the validator **and** these are the only two entries in `[ips_fixed]`, the validator will be left with no connectivity. This is because `[peer_private]` will enforce connections being made to only the entries in `[ips_fixed]`.

I think both these sections can be commented out, and should only be used if the validator has their own proxy(s) in front.

**Comment by jhaaaa** [comment]
Thank you, @alloyxrp! Working on addressing this - more soon.

**Comment by jhaaaa** [comment]
Addressed in PR #542. Thank you again for taking the time to raise this issue!
