### ISSUE TITLE
How do I create a multilingual document?

### ISSUE THREAD

**Issue by codedaily** [XRPLF/xrpl-dev-portal#541]
Hello. I have question.
How do I create a i18n document?
Have a nice day~

**Comment by ryangyoung** [comment]
Hi @codedaily, could you provide a little more context? Are you asking how to provide a translated version of a document within the XRPL Dev Portal?

**Comment by codedaily** [comment]
@ryangyoung  Yes. I want to translated version of document within the XRP Dev Portal.

**Comment by mDuo13** [comment]
We don't have the infrastructure in place yet, but we have [a translation plan](https://github.com/ripple/ripple-dev-portal/issues/526) that calls for translated Markdown files to be placed alongside the English-language documents.

For example, if the English document is in the file `concepts/introduction/intro-to-consensus.md`, then the Spanish version would be `concepts/introduction/intro-to-consensus.es.md`

If you want to get started, feel free to open a pull request adding such files, and I'll make them available when we have the infrastructure for showing translated versions.

**Comment by mDuo13** [comment]
Please direct further discussion of translations to #526 .
