### ISSUE TITLE
Updates to Installation Instructions for 1.3 release

### ISSUE THREAD

**Issue by mellery451** [XRPLF/xrpl-dev-portal#544]
We are making some non-trivial changes to our package repository build and infrastructure for the upcoming 1.3 release, so the docs need to change. I'll try to summarize here, but we'll probably have an ongoing discussion as we try to flesh-out the details.

For both package types, I think we need to advise that users do a *manual* upgrade from 1.2, which means:

* stop rippled
* Backup **DATA AND CONFIG FILES** - the location of the config is probably `/opt/ripple/etc/rippled.cfg`, but might be somewhere else if they moved it. The `validators.txt` file in the same location should be saved too. The data directory depends on their config/setup. All data directory files should be saved, including the node-db files.
* uninstall the previous package. For rpm packages, this probably involves `rpm -e rippled`. For things installed via alien on ubuntu, maybe there is an alien uninstall, or just use rpm? (TBD)
* install 1.3 as described below
* restore data and config files to desired location.
* NOTE: If you are just running a *stock server* with no config tweaks and don't care about the data you had before upgrade, then the data/config backup step is not needed.

These steps are specific to the 1.2-->1.3 upgrade. Future versions past 1.3 should not require these manual backup/restore steps.

## rpm installation ##

The repository and instructions for using it have changed. The steps are now something like:

```bash
<with sudo:>
yum -y update
yum -y install yum-utils
cat << REPOFILE > /etc/yum.repos.d/ripple.repo
[ripple-stable]
name=XRP Ledger Packages
baseurl=https://repos.ripple.com/repos/rippled-rpm/stable/
enabled=1
gpgcheck=0
gpgkey=https://repos.ripple.com/repos/rippled-rpm/stable/repodata/repomd.xml.key
repo_gpgcheck=1
REPOFILE
yum -y update
yum -y install rippled
```

(important note: the name used above `[ripple-stable]` is important in order for the update script we provide to work properly - it relies on this naming scheme specifically)

The system enable/start steps in the existing instructions can remain.

## deb package installation ##

We now have a native debian package - no more alien involved. The steps are:

```bash
<with sudo:>
apt -y update
apt -y install apt-transport-https ca-certificates wget gnupg
wget -q -O - "https://repos.ripple.com/repos/api/gpg/key/public" | apt-key add -
# Fingerprint: C001 0EC2 05B3 5A33 10DC 90DE 395F 97FF CCAF D9A2
echo "deb https://repos.ripple.com/repos/rippled-deb <DISTRO> stable" > /etc/apt/sources.list.d/ripple.list
apt -y update
apt-get -y install rippled
```

*Note:* `<DISTRO>` above is one of:

* xenial  (for ub 16.04)
* bionic  (for ub 18.04)
* stretch  (for debian stable/9)

These are currently the only distros we support, but that list will change in the future as we choose to add more debian distros.

I *believe* the daemon will start automatically after installation with deb - but this needs to be confirmed. If it does not, then we can duplicate the systemctl steps from the rpm instructions.

## automatic or manual updates ##

An update script is installed at `/opt/ripple/bin/update-rippled.sh`. This script can be invoked manually, or via cron. We provide a crontab file in `/opt/ripple/etc/update-rippled-cron` which can be enabled by creating a symlink to this file in `/etc/cron.d`

For manual updates on both distros, I think we can just recommend that users run the update script manually, as needed.

**Comment by mellery451** [comment]
@alloyxrp : I'd appreciate any feedback you might have on these notes and anything I might have missed. I'm happy to edit the description above as needed to correct/clarify. Thanks

**Comment by alloynetworks** [comment]
@mellery451 : Nit, the order is wrong in the debian instructions. It should be
```
<with sudo:>
apt -y update
apt -y upgrade
```

**Comment by mellery451** [comment]
@alloyxrp thanks - fixed.

**Comment by alloynetworks** [comment]
@mellery451 Since the repository URL is changing, IMO it makes sense to use something like `repos.ripple.com` instead of `mirrors1.ripple.com` . Packages need to be maintained on `mirrors.ripple.com` for at least a few releases after 1.3.0. Especially since the auto-upgrade nodes _may not_ make changes immediately. And other nodes could have it scripted as well.

**Comment by mellery451** [comment]
`repos.ripple.com` is now enabled - thanks @alloyxrp for the suggestion. Docs above have been updated accordingly.

**Comment by manojsdoshi** [comment]
Can we add steps to start and check the status of rippled as well to the docs: 

Enable rippled service:  **sudo systemctl enable rippled.service**
Start rippled:  **sudo systemctl start rippled.service**
Check the status of rippled: **sudo systemctl status rippled.service**

**Comment by alloynetworks** [comment]
Should we add documentation about how to use logrotate.d for rotating the `rippled` log file? This configuration could also be included in the packages @mellery451 ?
For example:
`/etc/logrotate.d/rippled`

```
/var/log/rippled/debug.log {
    missingok
    notifempty
    daily
    rotate 10
    copytruncate
    compress
    create 0644 rippled rippled
}
```

**Comment by mDuo13** [comment]
@alloyxrp I was wondering why my checker wasn't displaying the information for your file; turns out the checker is right and you have a recurring syntax error in your `toml` file. The `[[VALIDATORS]`, `[[ACCOUNTS]]`, `[[PRINCIPALS]]`, and `[[SERVERS]]` headings need to use _double_ square brackets. That's TOML syntax for "array entry" whereas single square brackets indicates a fixed object. This is a case where TOML doesn't really live up to the "Obvious" in its name.

This might be something I could add to the checker to look for.
