### ISSUE TITLE
secret key loss

### ISSUE THREAD

**Issue by shreeaanshG** [XRPLF/xrpl-dev-portal#558]
Hi Team,
I hope you are doing well. I have to generate an XRP address. I have Save XRP address and public key, private key save but secret loss so how can I get the secret key by using public key and private key. I need to help.

**Comment by MarkusTeufelberger** [comment]
The private key is derived from the secret. This is a one way operation. It is not possible to calculate a secret from a private key.

**Comment by intelliot** [comment]
It is not possible to get the secret, but it is possible to sign transactions. 

When using ripple-lib to sign a transaction, provide a keypair object to use for signing. (Requires ripple-lib 0.20.0 or higher.) This allows you to submit a payment without using a secret. For details see:

https://developers.ripple.com/rippleapi-reference.html#sign
