### ISSUE TITLE
transaction issues xrp 

### ISSUE THREAD

**Issue by shreeaanshG** [XRPLF/xrpl-dev-portal#559]
Hi Team,

I hope, You are doing Great.I have generated XRP address using to **ripple-lib** lib. (address, secret, public key, private key).I am not able to transfer coin. I am getting error which says that it needs destination tab I need to help.
--------------------------error---------------------------
1D1C42DEF57B6EF068C53BA75D8906E69DA03CFABB2E437C7589040FF4D0C17A
{
  "resultCode": "tecNO_DST_INSUF_XRP",
  "resultMessage": "Destination does not exist. Too little XRP sent to create it."
}

**Comment by alloynetworks** [comment]
This type of issue is best posted in the main rippled repo.

However, this message likely means that you have sent *less than 20 XRP* to a not yet activated account. Please try with at least 20 XRP - remember that 20 XRP will remain in reserve.

**Comment by shreeaanshG** [comment]
Hi Team,
I hope, You are All doing Great. The resolution that you gave is working. But only the problem is for sending 20 XRP one should have atleast 20 XRP in reserve in the wallet. please tell me how to send my whole XRP balance in another wallet.

**Comment by intelliot** [comment]
Currently, the reserve cannot be sent to another address. See https://developers.ripple.com/reserves.html
