### ISSUE TITLE
XRP transaction issues

### ISSUE THREAD

**Issue by shreeaanshG** [XRPLF/xrpl-dev-portal#562]
Hi Team,
I hope, You are All doing Great. The resolution that you gave is working. But only the problem is for sending 20 XRP one should have atleast 20 XRP in reserve in the wallet. please tell me how to send my whole XRP balance in another wallet.

**Comment by alloynetworks** [comment]
This is the repository for the **documentation** for the dev portal. Please visit https://github.com/ripple/rippled - for future questions.
However, you currently cannot send your entire balance to another wallet. The 20 XRP will remain in reserve in the original (sending) wallet.
