### ISSUE TITLE
RippleAPI JS Payment Transaction

### ISSUE THREAD

**Issue by xrpinnovations** [XRPLF/xrpl-dev-portal#574]
The payment transaction type [documented here](https://developers.ripple.com/rippleapi-reference.html#payment) appears to include a duplicate:

destination. address | address | The address to receive at.
destination. address | address | The address to send to.

**Comment by mDuo13** [comment]
When there's a new ripple-lib release containing the fix, we can update the version referenced in this repo's config and resolve this issue that way.
