### ISSUE TITLE
Add account-based lookup to xrp-ledger.toml tool

### ISSUE THREAD

**Issue by mDuo13** [XRPLF/xrpl-dev-portal#576]
The xrp-ledger.toml checker can do domain verification for an account if you give it a URL, but (as [Markus T. mentioned](https://github.com/ripple/ripple-dev-portal/pull/572#issuecomment-501476099)) it would be really cool to do lookups the other way—enter an XRP Ledger address, look up the `Domain` associated with that address (in the mainnet or test net) and then check the `xrp-ledger.toml` file associated with it.

**Comment by q411** [comment]
https://github.com/ripple/xrpl-dev-portal/pull/572

**Comment by mDuo13** [comment]
Fixed by #1644
