### ISSUE TITLE
Metadata for link unfurling

### ISSUE THREAD

**Issue by mDuo13** [XRPLF/xrpl-dev-portal#579]
We should update the templates for doc pages to provide metadata for apps such as Facebook, Slack, Twitter, and others to present when they "unfurl" a link.

[The Slack Developer Blog post on unfurling](https://medium.com/slack-developer-blog/everything-you-ever-wanted-to-know-about-unfurling-but-were-afraid-to-ask-or-how-to-make-your-e64b4bb9254) contains a bunch of the relevant technical info on the kinds of properties you can provide to improve link unfurling.

We don't want to do a separate oEmbed server, but there's a lot of room to provide more info via `<meta>` tags in the HTML, following the Facebook OpenGraph, Twitter cards, etc. standards.

**Comment by q411** [comment]
https://github.com/ripple/xrpl-dev-portal/labels/web%20dev

**Comment by q411** [comment]
https://medium.com/slack-developer-blog/everything-you-ever-wanted-to-know-about-unfurling-but-were-afraid-to-ask-or-how-to-make-your-e64b4bb9254

**Comment by mDuo13** [comment]
Fixed in https://github.com/ripple/xrpl-dev-portal/pull/910 and https://github.com/ripple/xrpl-dev-portal/pull/928
