### ISSUE TITLE
Tutorial: Configure a Private Server

### ISSUE THREAD

**Issue by mDuo13** [XRPLF/xrpl-dev-portal#580]
https://xrpl.org/peer-protocol.html#configuring-a-private-server is the start of a tutorial for how to configure your server as a private peer. However, it could really stand to be improved.

The existing docs for configuring a validator to  [Connect to the network with proxies](https://xrpl.org/run-rippled-as-a-validator.html#connect-using-proxies) is almost exactly what this guide should describe. In fact, it might be best to use that as a starting point, then replace that with a link to the resulting doc.

The doc should include:

- Step by step information (prerequisites, what file to edit, when to restart the server, etc.)
- Describe the recommended (and other possible) network infrastructure, with diagrams _and_ text.

**Comment by q411** [comment]
https://github.com/ripple/xrpl-dev-portal/labels/new%20topic

**Comment by q411** [comment]
https://xrpl.org/run-rippled-as-a-validator.html#connect-using-proxies

**Comment by q411** [comment]
https://xrpl.org/peer-protocol.html#configuring-a-private-server

**Comment by mDuo13** [comment]
https://xrpl.org/configure-a-private-server.html added by #750
