### ISSUE TITLE
Add "Invariant Checking" concept & reference articles

### ISSUE THREAD

**Issue by mDuo13** [XRPLF/xrpl-dev-portal#587]
Add a page summarizing [Invariant Checking](https://xrpl.org/blog/2017/invariant-checking.html) - why it exists, how it works from a high level, etc.

As a separate page or section of the same page, add a comprehensive list of every invariant check implemented.

**Comment by q411** [comment]
https://github.com/ripple/xrpl-dev-portal/pull/880
