### ISSUE TITLE
Tutorial: Migrate data from the ledger store to the shard store

### ISSUE THREAD

**Issue by mDuo13** [XRPLF/xrpl-dev-portal#588]
Tutorial for how to use the `--nodetoshard` option to migrate data from the ledger store into the shard store.

Requires that your ledger store already has at least one full shard's worth of ledger history. You must have a shard store configured and the disk it's on must have space to store the data to be copied from the ledger store (so if they're on the same disk, you'll need enough free space to store an additional copy of the data at least temporarily).

The tutorial should make it clear how you know when the copy/import into the shard store is done. Optionally, after that happens, you can delete the data from the ledger store and configure it to store less history.

SME: @miguelportilla 

Acceptance Criteria:

- New document in the "Tutorials" section
- Step by step instructions with authentic code samples / example output where appropriate

**Comment by q411** [comment]
https://github.com/miguelportilla
https://github.com/ripple/xrpl-dev-portal/labels/new%20topic

**Comment by mDuo13** [comment]
No demand for this at the moment and the future of history sharding is not exactly settled at the moment. We can revisit this in the future if there's demand.
