### ISSUE TITLE
Tutorial: Choose and Set a TickSize

### ISSUE THREAD

**Issue by mDuo13** [XRPLF/xrpl-dev-portal#592]
Gateways that issue in the XRP Ledger may benefit (and the ledger itself can benefit) if they set a [TickSize](https://xrpl.org/ticksize.html) value on their issuing account, reducing the incentive for traders to churn out redundant offers at exchange rates that are only microscopically "better" than comparable offers.

Tutorial should include:

- Prerequisites (that you be an issuer)
- Step-by-step guide to deciding on a ticksize, sending the transaction to set it, and checking that your ticksize is set.
- Links to relevant documents (likely the gateway guide)

**Comment by q411** [comment]
https://xrpl.org/ticksize.html
https://github.com/ripple/xrpl-dev-portal/labels/new%20topic

**Comment by amarantha-k** [comment]
The following tutorial addresses choosing and setting TickSize: https://xrpl.org/issue-a-fungible-token.html#3-configure-issuer-settings
