### ISSUE TITLE
Ed25519 signature guide(s)

### ISSUE THREAD

**Issue by mDuo13** [XRPLF/xrpl-dev-portal#595]
Similar to the Multi-Signing tutorials, but for using Ed25519 signatures. Should include:

- how to generate Ed25519 keys
- how to set Ed25519 keys as regular key
- how to fund an Ed25519 address
- how to sign a transaction with an Ed25519 (regular/master) key
- how to add an Ed25519 sig to a multi-signature
- how to sign payment channel claims with Ed25519 (may not be possible with rippled due to a bug?)
- links to relevant documentation like [cryptographic keys#signing algorithms](https://xrpl.org/cryptographic-keys.html#signing-algorithms) and how to disable the master key ( #569 )

**Comment by q411** [comment]
https://xrpl.org/cryptographic-keys.html#signing-algorithms

**Comment by q411** [comment]
https://github.com/ripple/xrpl-dev-portal/labels/new%20topic

**Comment by amarantha-k** [comment]
This looks to be reasonably well-covered in the documentation.
