### ISSUE TITLE
RippleAPI Docs References to 'Ripple' accounts

### ISSUE THREAD

**Issue by xrpinnovations** [XRPLF/xrpl-dev-portal#600]
The JS documentation has multiple references to 'ripple' address rather than XRP address. Consider changing this for consistent terminology. :-)

Examples below:

https://xrpl.org/rippleapi-reference.html#amount
https://xrpl.org/rippleapi-reference.html#getbalances

Counterparty - Optional The **Ripple** address of the account that owes or is owed the funds (omitted if currency is "XRP" or "drops")

https://xrpl.org/rippleapi-reference.html#getbalancesheet
https://xrpl.org/rippleapi-reference.html#getorders

Address - The **Ripple** address of the account to get the balance sheet of.

https://xrpl.org/rippleapi-reference.html#getpaths

pathfind.source. address - The **Ripple** address of the account where funds will come from.

**Comment by mDuo13** [comment]
Good catch. The docs for RippleAPI/ripple-lib are pulled directly from [upstream](https://github.com/ripple/ripple-lib/tree/develop/docs/src) so the changes will have to go there first.

**Comment by xrpinnovations** [comment]
Has there been any consideration of rebranding RippleAPI to XrpAPI? @Joelkatz @nbougalis

**Comment by mDuo13** [comment]
Has there been consideration? Absolutely.

Have we reached a conclusion about when/how to rename every "ripple" thing to be called XRP something? Not yet.

**Comment by xrpinnovations** [comment]
Good to hear, thanks!!

**Comment by MarkusTeufelberger** [comment]
Not everything is "XRP" by the way and just renaming everything "Ripple" to "XRP" just would create the exact same confusion (name of the asset, name of the blockchain...).

**Comment by xrpinnovations** [comment]
Yeah I understand not everything can be renamed and the great XRP ledger is maintained by ripple hence the name rippled for the version of software in use by validators. The only reason I raised the point above is to ensure we have absolute clarity on what is XRP (or XRPL) and what is maintained (or suggested) by Ripple if that makes sense?? Obviously to provide legal/regulatory clarity. PS I thought the blockchain was named the XRP Ledger? please correct me if I'm wrong.

**Comment by yxxyun** [comment]
https://xrpl.org/xrp.html
Naming section

**Comment by mDuo13** [comment]
Opened https://github.com/ripple/ripple-lib/pull/1023 to fix the "Ripple address" thing in the ripple-lib docs.

**Comment by mDuo13** [comment]
This is done in the latest version
