### ISSUE TITLE
WebSocket API Tool "Try It!" loads raw template

### ISSUE THREAD

**Issue by iroskam** [XRPLF/xrpl-dev-portal#609]
The "Try It!" button loads the raw template-websocket-api-tool.html on most methods.  On the loaded page the client doesn't connect.

![broken_try_it_account_lines](https://user-images.githubusercontent.com/1930056/60387316-aa30e080-9a4d-11e9-8d84-5cce593ab7eb.png)

"Try It!" button is broken on the following pages:
account_currencies, account_info, account_lines, account_offers, account_tx, ledger_closed, ledger_current, ledger_entry, sign, transaction_entry, tx_history, book_offers, ripple_path_find, server_info, server_state

"Try It!" button works on the following pages:
ledger, submit, tx, subscribe, unsubscribe, ping

**Comment by iroskam** [comment]
All methods work when navigating directly from the websocket-api-tool.html
Links on "Try It!" have an '_'.  Links on websocket-api-tool.html have a '-'

**Comment by mDuo13** [comment]
Thanks for catching this. I'll have the fix merged & deployed within a day or so.
