### ISSUE TITLE
TestNetwork not work now

### ISSUE THREAD

**Issue by ErickMarlo** [XRPLF/xrpl-dev-portal#622]
I was generate credentials but i see error:
There was an error with the Ripple Test Net, please try again.

How to fix it?

**Comment by intelliot** [comment]
This error has been resolved. Feel free to try again now.

**Comment by xrpinnovations** [comment]
Can confirm the faucet works via https://xrpl.org/xrp-test-net-faucet.html and the legacy site https://faucet.altnet.rippletest.net/accounts for posts :-)
