### ISSUE TITLE
Extend history sharding tutorial with download_shard and crawl_shards commands

### ISSUE THREAD

**Issue by mDuo13** [XRPLF/xrpl-dev-portal#629]
When the [Configure History Sharding tutorial](https://xrpl.org/configure-history-sharding.html) was written, the `download_shard` and `crawl_shards` commands weren't available. Now that they are, the tutorial should be updated to use those to simplify the steps and provide next steps where applicable.

**Comment by q411** [comment]
https://xrpl.org/configure-history-sharding.html

**Comment by q411** [comment]
https://github.com/ripple/xrpl-dev-portal/labels/help%20wanted
