### ISSUE TITLE
Update Ubuntu build instructions for Ubuntu 16.04

### ISSUE THREAD

**Issue by mDuo13** [XRPLF/xrpl-dev-portal#672]
Building `rippled` 1.3.1 requires gcc 7 or higher, but Ubuntu 16.04 ships with gcc 5.3.

To build rippled on Ubuntu 16.04, users will have to [install gcc 7](https://askubuntu.com/questions/859256/how-to-install-gcc-7-or-clang-4-0), possibly from a [PPA](https://launchpad.net/~ubuntu-toolchain-r/+archive/ubuntu/test). Investigate, test, and update the [Ubuntu build instructions](https://xrpl.org/build-run-rippled-ubuntu.html) to call out the extra steps for building on Ubuntu 16.04, which AFAIK we'll continue to support until early 2021 since that's when Canonical's support transitions from "Maintenance updates" to "Extended security maintenance for customers"

**Comment by mDuo13** [comment]
This ticket addresses https://github.com/ripple/rippled/issues/3029

**Comment by q411** [comment]
https://github.com/ripple/rippled/issues/3029

**Comment by q411** [comment]
https://github.com/ripple/xrpl-dev-portal/labels/help%20wanted

**Comment by mDuo13** [comment]
Ubuntu 16.04 is past EOL and no longer supported, so this is not needed
