### ISSUE TITLE
Testnet faucet is not working

### ISSUE THREAD

**Issue by donamk** [XRPLF/xrpl-dev-portal#677]
I tried to get some testnet ripple using https://xrpl.org/xrp-test-net-faucet.html but it is not working for a few days.

I got an errror message `There was an error with the Ripple Test Net, please try again.`
and the HTTP 503 error code from https://faucet.altnet.rippletest.net/accounts

**Comment by mDuo13** [comment]
Acknowledged. We'll have it fixed as soon as we can. (And I hope we can add better monitoring so users like you don't have to be the ones to notice in the future.)

**Comment by donamk** [comment]
Does anyone give me some testnet ripple `rf66MSf7nYWDCr78prktEu1ZLpn7y3A7to`?

**Comment by intelliot** [comment]
@donamk `rf66MSf7nYWDCr78prktEu1ZLpn7y3A7to` has been funded with test XRP. The [testnet faucet](https://xrpl.org/xrp-testnet-faucet.html) is also available again, so feel free to use it for additional test accounts or funds.

See the dev blog for [details about the testnet reset](https://xrpl.org/blog/2019/testnet-reset.html).
