### ISSUE TITLE
Proposed revisions to Stand-Alone Mode tutorials

### ISSUE THREAD

**Issue by mDuo13** [XRPLF/xrpl-dev-portal#683]
1. Rename the category from "Use rippled in Stand-Alone Mode" to "Test rippled Offline in Stand-Alone Mode"

2. Add a "Test amendments in Stand-Alone Mode" tutorial that shows how to use `[feature]` to try out amendments that aren't enabled yet

3. Make "Advance the ledger in Stand-Alone Mode" slightly more tutorialized and change the "Note" to a "Tip" callout.

4. [Start a new Genesis Ledger in Stand-Alone Mode](https://xrpl.org/start-a-new-genesis-ledger-in-stand-alone-mode.html) edits:

    It would be handy if this page included a sample of how to config the genesis ledger to match production's fee schedule, namely:

        [voting]
        account_reserve=20000000
        owner_reserve=5000000

**Comment by q411** [comment]
https://xrpl.org/start-a-new-genesis-ledger-in-stand-alone-mode.html
https://github.com/ripple/xrpl-dev-portal/labels/organization
