### ISSUE TITLE
Address Encoding Diagram Incorrectly Says SHA256 of RIPEMD160

### ISSUE THREAD

**Issue by iroskam** [XRPLF/xrpl-dev-portal#697]
The address encoding diagram on content/concepts/payment-system-basics/accounts/accounts.md line 99 has the line from Public Key to account_id incorrectly labeled SHA256 of RIPEMD160.  Label should be RIPEMD160 of SHA256 as indicated in the source example.

**Comment by mDuo13** [comment]
Yep, already reported as #624. I have [a branch that fixes this](https://github.com/ripple/xrpl-dev-portal/compare/master...mDuo13:doc2359) (among other things) in progress.

**Comment by mDuo13** [comment]
(Going to close this one since it's a duplicate.)
