### ISSUE TITLE
Checks tutorials improvements

### ISSUE THREAD

**Issue by mDuo13** [XRPLF/xrpl-dev-portal#699]
The various [Checks tutorials](https://xrpl.org/use-checks.html) could use some work. In particular, many steps don't have RippleAPI JavaScript examples, or have an inconsistent mix of commandline and non-commandline examples.

The framework established for the "Send XRP" tutorial could be used to make these tutorials fully interactive. (Depending on when the Checks amendment gets enabled, it might be easiest to do on the Devnet rather than the Testnet, since Checks aren't enabled on Testnet anymore, which matches production's status.)

That would probably be a better set of improvements than just changing the hashes from some examples, [as started here](https://github.com/ripple/xrpl-dev-portal/compare/master...mDuo13:fix_hashes_2?expand=1).

**Comment by q411** [comment]
https://github.com/ripple/xrpl-dev-portal/pull/663

**Comment by q411** [comment]
https://github.com/ripple/xrpl-dev-portal/labels/organization

**Comment by amarantha-k** [comment]
Closing without updates as this issue is captured in the more recent and up-to-date issue #1206.
