### ISSUE TITLE
Define SHA-512half

### ISSUE THREAD

**Issue by iroskam** [XRPLF/xrpl-dev-portal#708]
[Basic data types](https://xrpl.org/basic-data-types.html#hashes) has a note of how SHA-512half is similar to SHA-512/256.  However, there is no definition of what exactly SHA-512half is.  Since SHA-512half is used quite often it would be helpful to define which half is being used from the SHA-512 hash.

**Comment by mDuo13** [comment]
Right above the note, the paragraph has the definition you're looking for, doesn't it?

> This value is typically calculated as a "SHA-512Half", which calculates a SHA-512 hash from some contents, then takes the first half of the output. (That's 256 bits, which is 32 bytes, or 64 characters of the hexadecimal representation.)

**Comment by iroskam** [comment]
Damn, sorry.  I skipped right over the words "first half".
