### ISSUE TITLE
Websocket Tool - account_lines not working

### ISSUE THREAD

**Issue by movitto** [XRPLF/xrpl-dev-portal#709]
Perhaps related to #609 (not sure, the other methods mentioned there seem to be working) but when the user attempts to "Try it" on the "account_lines" page the site does not provide access to this API method.

Can be replicated by clicking "Try it" here: https://xrpl.org/account_lines.html

Also note there is no account_lines option on the WebSocket tool API methods navigation:

https://xrpl.org/websocket-api-tool.html#account_lines

**Comment by mDuo13** [comment]
That's odd, but you're correct.

Should be an easy fix—just have to add an account_lines example to https://github.com/ripple/xrpl-dev-portal/blob/master/assets/js/apitool-methods-ws.js
