### ISSUE TITLE
Describe recommended user/permissions setup

### ISSUE THREAD

**Issue by mDuo13** [XRPLF/xrpl-dev-portal#712]
Inspired by #710, the dev portal should probably have a page describing the recommended user setup (a dedicated low-permissions `rippled:rippled` group & user) for running `rippled` as implemented by the supported packages. That would make it easier to build a similar setup on non-supported distros.

It could list the files/directories that the user owns (including recommended paths for databases, etc.) and any other permissions the user needs (e.g. to bind whatever ports rippled needs)

**Comment by q411** [comment]
https://github.com/ripple/xrpl-dev-portal/pull/710

**Comment by q411** [comment]
https://github.com/ripple/xrpl-dev-portal/labels/help%20wanted
https://github.com/ripple/xrpl-dev-portal/labels/new%20topic
