### ISSUE TITLE
Stale Ripple Consensus link in consensus.html

### ISSUE THREAD

**Issue by stanislavkozlovski** [XRPLF/xrpl-dev-portal#723]
The Ripple Consensus Video in https://github.com/ripple/xrpl-dev-portal/blob/master/content/concepts/consensus-network/consensus.md#see-also is not available anymore

**Comment by q411** [comment]
https://github.com/ripple/xrpl-dev-portal/blob/master/content/concepts/consensus-network/consensus.md#see-also

**Comment by intelliot** [comment]
Fixed by https://github.com/XRPLF/xrpl-dev-portal/pull/1317
