### ISSUE TITLE
Please add a link to the location of the proto files for the gRPC API

### ISSUE THREAD

**Issue by richardpringle** [XRPLF/xrpl-dev-portal#818]
The gRPC docs for `rippled` have a whole page dedicated to starting the gRPC server, but there is no mention of where to find the proto files to talk to the server.

Here's the doc page: https://xrpl.org/configure-grpc.html
It's missing a link to the proto files: https://github.com/ripple/rippled/tree/develop/src/ripple/proto/org/xrpl/rpc/v1

Awesome decision to use gRPC! I'm sure it's going to be much nicer interacting with `rippled` with a typed interface!

**Comment by mDuo13** [comment]
I have several more gRPC documents planned, including an overview that lists the available methods and a quickstart to using it as a client.

I'll make sure at least one of them links these files, thanks!

**Comment by q411** [comment]
https://xrpl.org/configure-https://github.com/ripple/rippled/tree/develop/src/ripple/proto/org/xrpl/rpc/v1grpc.html
