### ISSUE TITLE
XRPL Explorer shows "official" XRP symbol next to IOUs with currency code 'xrp'

### ISSUE THREAD

**Issue by nixer89** [XRPLF/xrpl-dev-portal#846]
I just issued my own 'xrp' on the XRPL test net.
Checking the recipient account on testnet.xrpl.org explorer shows the IOU with the "official" XRP symbol next to the amount:

![grafik](https://user-images.githubusercontent.com/25486793/82441300-05bcf000-9a9e-11ea-8c41-226cf71a4f3d.png)

I think this should be changed (no symbol like other IOU) to avoid people "selling" those IOU as 'real' XRP.

best,
nixerFFM

**Comment by nixer89** [comment]
ps: also the TrustSett transaction contains a symbol which is quite misleading. "XRP" cannot be issued :-)

![grafik](https://user-images.githubusercontent.com/25486793/82441700-9c89ac80-9a9e-11ea-80de-67ccd3587b7f.png)

**Comment by ximinez** [comment]
@nixer89 Could you provide a link to the TrustSet transaction that isn't in an image?

**Comment by nixer89** [comment]
Hi @ximinez, yes of course. Here is the trust set transaction. (I've created the IOU 'xrp' - all lower case, which is not forbidden 😇)

https://testnet.xrpl.org/transactions/0655538333F8376BADC365076E3C74E58EF8AD378E903E5130A2F06FC3DFF355

And here is the account:
https://testnet.xrpl.org/accounts/rDn65vS7Hw2g4WHMTHdgbQ3HTyaqQ7ADmJ

**Comment by mDuo13** [comment]
Yes, the Explorer should not show the icon there. Doing so is misleading and dangerous.

**Comment by intelliot** [comment]
We have fixed this issue. Thank you for reporting it!
