### ISSUE TITLE
Multi-signing doc improvements

### ISSUE THREAD

**Issue by mDuo13** [XRPLF/xrpl-dev-portal#877]
The [multi-signing doc](https://xrpl.org/multi-signing.html) should talk more about the high-level concepts around multi-signing:

- Signer weights and quorum and how they relate
- High-level overview of how to use multi-signing, noting important stuff like how multi-signing adds a new way of authorizing transactions so if you want to be exclusively multi-signing you have to disable the ways of signing
- Maybe some more detailed descriptions of how you might accomplish some of the use cases described in the intro bullets

**Comment by mDuo13** [comment]
The multi-signing doc should also have examples using RippleAPI—for example, the [combine() function](https://xrpl.org/rippleapi-reference.html#combine)—to collect and assemble multi-signatures

**Comment by q411** [comment]
https://xrpl.org/rippleapi-reference.html#combine

**Comment by mDuo13** [comment]
Duplicate of #685
