### ISSUE TITLE
DestinationNode is missing from PayChannel ledger object documentation

### ISSUE THREAD

**Issue by cjcobb23** [XRPLF/xrpl-dev-portal#892]
`DestinationNode` is a field of the `PayChannel` ledger object, but is not documented on [https://xrpl.org/paychannel.html](https://xrpl.org/paychannel.html)

**Comment by mDuo13** [comment]
Aha, this was [added by fixPayChanRecipientOwnerDir](https://github.com/ripple/rippled/commit/e33ac1d45090891bbb38ad96817a96f6106c8583).

**Comment by q411** [comment]
https://github.com/ripple/xrpl-dev-portal/labels/chttps://github.com/ripple/xrpl-dev-portal/labels/help%20wantedontent%20updates

**Comment by mDuo13** [comment]
Fixed by #1182. However, I suspect the underlying issue is that the order of the fields in the table is inconsistent which makes it easy to miss the existing documentation. I created #1183 as a follow-up to fix that.
