### ISSUE TITLE
Update documentation to remove the validateShards command-line option

### ISSUE THREAD

**Issue by miguelportilla** [XRPLF/xrpl-dev-portal#916]
The `validateShards` command-line option was deprecated in [1.7.0-b3,](https://github.com/ripple/rippled/pull/3631) [PR 3489](https://github.com/ripple/rippled/pull/3489). References to the option should be removed from the rippled documentation.

**Comment by mDuo13** [comment]
Relevant doc: [rippled Commandline Usage Reference](https://xrpl.org/commandline-usage.html)
