### ISSUE TITLE
Dead Graph Link ripplecharts.com

### ISSUE THREAD

**Issue by TrashAccount3424** [XRPLF/xrpl-dev-portal#930]
On https://xrpl.org/xrp-ledger-rpc-tool.html If you search for something the result show 2 links a Permalink and a Graph link.
The second goes to https://www.ripplecharts.com/#/graph/r... which seems to be dead.

I assume it should be changed to https://xrpcharts.ripple.com/#/graph/r...

https://github.com/ripple/xrpl-dev-portal/blob/bf4180ad52046c5a1dbbeac01ddfadb4bd9ea9f7/assets/js/rpc-tool.js#L55

**Comment by q411** [comment]
https://github.com/ripple/xrpl-dev-portal/issues/988

**Comment by mDuo13** [comment]
Fixed in #998
