### ISSUE TITLE
Document Reporting Mode

### ISSUE THREAD

**Issue by cjcobb23** [XRPLF/xrpl-dev-portal#937]
Soon, many of Ripple's publicly accessible servers will be running in reporting mode. Reporting mode makes some changes to the published API. This issue is to document reporting mode, mainly what it is and what the API changes are.

**Comment by cjcobb23** [comment]
Reporting mode was merged as part of 1.7-b11 (https://github.com/ripple/rippled/pull/3739). We have two reporting mode servers running inside s1, handling client requests. Let's document the API differences.

**Comment by q411** [comment]
https://github.com/ripple/rippled/pull/3739

**Comment by mDuo13** [comment]
This is done: https://xrpl.org/rippled-server-modes.html#reporting-mode
