### ISSUE TITLE
account_info signer_list does not match API response

### ISSUE THREAD

**Issue by nkramer44** [XRPLF/xrpl-dev-portal#938]
The docs for the [account_info response fields](https://xrpl.org/account_info.html#response-format) say that `signer_lists` should exist at the root level of the response.  However, the actual API response puts `signer_lists` under `account_data`, which is an `AccountRoot` object.  

I'm not sure if this is a bug in the rippled code or in the docs, but it's a bit misleading as is, because the docs for `AccountRoot` do not mention `signer_lists`.

**Comment by mDuo13** [comment]
Yes, signer lists are not part of the `AccountRoot` object, so in the code this is either a bug or poor API design, but that is what the code does, so the docs should probably fix this. (And we should also change this in a future version of the API.)

**Comment by Frassle** [comment]
Does it make sense to move this field as part of the api_version:2 work currently being done on rippled?

**Comment by mDuo13** [comment]
Yes, I think it does.

**Comment by q411** [comment]
https://github.com/ripple/rippled/pull/3770

**Comment by intelliot** [comment]
This will be addressed in api_version 2. Details: https://github.com/xrplf/rippled/blob/develop/API-CHANGELOG.md
