### ISSUE TITLE
MacOS install instructions use the ruby homebrew installer which is deprecated.

### ISSUE THREAD

**Issue by cancelself** [XRPLF/xrpl-dev-portal#940]
https://xrpl.org/build-run-rippled-macos.html

dmp@dmpmac ~ % ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
Warning: The Ruby Homebrew installer is now deprecated and has been rewritten in
Bash. Please migrate to the following command:
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"

**Comment by q411** [comment]
https://raw.githubusercontent.com/Homebrew/install/master/install.sh

**Comment by q411** [comment]
https://raw.githubusercontent.com/Homebrew/install/master/install

**Comment by intelliot** [comment]
[Updated build instructions can be found here](https://github.com/XRPLF/rippled/blob/release/BUILD.md)
