### ISSUE TITLE
deprecation label on generateAddress should contain context

### ISSUE THREAD

**Issue by Mark-Isbell** [XRPLF/xrpl-dev-portal#945]
Since it's one of the API endpoints that is referenced in the introduction, I think it's important to include context around the deprecation label.  

Something like:  "This API is marked as deprecated to encourage developers of new applications ot use the newer, more flexible generateXAddress API endpoint instead. The generateAddress API will not be removed."

ALSO ... not sure about this part, but the definition implies that options can include "test" and "includeClassicAddress."  Not sure if that's accurate or not, but can this part be checked as well.

**Comment by q411** [comment]
https://github.com/Mark-Isbell

**Comment by mDuo13** [comment]
This applies to the ripple-lib 1.x documentation, which is now deprecated in favor of xrpl.js library. The new [Wallet class](https://js.xrpl.org/classes/Wallet.html) provides the requested options in a non-deprecated format.
