### ISSUE TITLE
A secondary layout with white background and black text please

### ISSUE THREAD

**Issue by timothyTheCoder** [XRPLF/xrpl-dev-portal#950]
A secondary layout would be great for people who have difficulties to read white text on a black background. Have a secondary layout with black text and white layout please.

Thanks

**Comment by mDuo13** [comment]
I built the doc pages so they could hopefully switch between themes fairly easily, so this shouldn't be too difficult to do. The graphic elements associated mostly with the Learn/Explore pages are a little more challenging.

**Comment by mDuo13** [comment]
The light mode theme is almost done, pending a design review.

**Comment by mDuo13** [comment]
This went live recently (2021-09-02)
