### ISSUE TITLE
Document nodetoshard_status

### ISSUE THREAD

**Issue by mDuo13** [XRPLF/xrpl-dev-portal#966]
Tracking ticket for https://github.com/ripple/rippled/pull/3709 docs

**Comment by q411** [comment]
https://github.com/ripple/xrpl-dev-portal/milestone/2https://github.com/ripple/xrpl-dev-portal/labels/new%20topic

**Comment by q411** [comment]
https://github.com/ripple/rippled/pull/3709

**Comment by SirJosh1987** [comment]
What do I do? I have guessed every thing I’ve done

**Comment by mDuo13** [comment]
Fixed by https://github.com/XRPLF/xrpl-dev-portal/pull/1249
