### ISSUE TITLE
Article/FAQ debunking Freeze-related myths

### ISSUE THREAD

**Issue by mDuo13** [XRPLF/xrpl-dev-portal#983]
There's a lot of FUD out there on the topic of the XRP Ledger's freeze feature. The [actual article on the feature](https://xrpl.org/freezes.html) is almost comically overwhelmed with statements about what can't happen but doesn't directly address the claims and misinformation.

A blog post or FAQ dedicated to myths about the freeze feature might be a better way to address some of the specific misunderstandings while leaving the main article about the feature a little simpler. It's a challenging area (in part because so many people are willfully motivated to believe what they want to be true about XRP) but it would probably help understanding to break things up this way.

While we're at it, it might also be useful to split off the technical details around freezing/unfreezing into separate tutorials and update them. They could even be interactive!

**Comment by q411** [comment]
https://github.com/ripple/xrpl-dev-portal/pull/961

**Comment by mDuo13** [comment]
https://xrpl.org/common-misconceptions-about-freezes.html
