### ISSUE TITLE
Terminology change: "issued currency" → "token"

### ISSUE THREAD

**Issue by mDuo13** [XRPLF/xrpl-dev-portal#984]
The term "token" is widely used in the cryptocurrency dev community to describe digital assets like those we call "issued currencies" on the XRP Ledger. (The term "IOUs" has also been used to describe the XRP Ledger's issued currencies, but has long been discouraged.) It would make sense to migrate to using this terminology preferentially in the docs.

[XRPL Labs](https://twitter.com/XRPLLabs/status/1361216610640547842) suggests calling them "tokens" (as in "tokens issued on the XRP Ledger" depending on the context) because they can take a variety of forms and have a variety of roles:

- "stablecoins" or "IOUs" pegged to a specific fiat currency are the traditional example. The [gateway guide](https://xrpl.org/become-an-xrp-ledger-gateway.html) is mostly about this use case.
- arbitrary assets with no inherent off-ledger attachments. (The [Allvor](https://allvor.org/) project hasn't updated lately, but they were one of the earlier projects to really try this on XRPL.)
- [non-fungible tokens](https://github.com/ripple/xrpl-dev-portal/pull/978)—especially XLS-14d and 19d ones. (XLS-20d non-fungible tokens have their own, separate, ledger structures)
- representations of non-currency assets such as gold bullion, securities, derivatives, etc. Almost anything is possible. (Whether it's legal and advisable is a different question.)

**Comment by q411** [comment]
https://github.com/ripple/xrpl-dev-portal/labels/organization

**Comment by mDuo13** [comment]
Aside: a "token" issued on the ledger is not to be confused with a "validator token" (i.e. an ephemeral key and related info combined into a string you paste into your config file)
