### ISSUE TITLE
The host ripplecharts.com is unknown or is not available.

### ISSUE THREAD

**Issue by kchaot** [XRPLF/xrpl-dev-portal#988]
https://github.com/ripple/xrpl-dev-portal/blob/3d2795279241b27d6352c8fafe944478e4351edf/assets/js/rpc-tool.js#L55

- ripplecharts.com vs. xrpcharts.ripple.com ?

**Comment by TrashAccount3424** [comment]
already reported #930

**Comment by mDuo13** [comment]
Closing this as a duplicate then
