### ISSUE TITLE
Reporting mode setup instructions

### ISSUE THREAD

**Issue by mDuo13** [XRPLF/xrpl-dev-portal#990]
The [in-repo build instructions](https://github.com/ripple/rippled/tree/develop/Builds/linux) have the build instructions (additional requirements, `-Dreporting=ON`.

Should also talk about config differences and changes other services you have to be running to get it to work, including:

- gRPC connection to a `rippled` peer in P2P Mode
- PostgreSQL
- Cassandra (optional, can use NuDB instead, but one Cassandra instance can be shared)

Plus any commandline flags/options specific to reporting mode

**Comment by q411** [comment]
https://github.com/ripple/xrpl-dev-portal/milestone/1

**Comment by q411** [comment]
https://github.com/ripple/xrpl-dev-portal/labels/new%20topic

**Comment by q411** [comment]
https://github.com/ripple/rippled/tree/develop/Builds/linux

**Comment by mDuo13** [comment]
Fixed by #1288
