### ISSUE TITLE
GetTransactions API method doesn't return Account deletion transaction

### ISSUE THREAD

**Issue by davidkralprofinit** [XRPLF/xrpl-dev-portal#999]
Hello,

I would like to ask if https://xrpl.org/rippleapi-reference.html#gettransactions method can return account deletion transation (for instance https://xrpscan.com/tx/6FF03FF338964206E1610A3411F06CCFD119BD9031C2B6CE2E46E053B4015891). Our method usage is with parametrs:
 - options. maxLedgerVersion
 - options. minLedgerVersion
 - options. excludeFailures

We are not using https://xrpl.org/rippleapi-reference.html#transaction-types in filter (the list doesn't contain account deletion type)

Thank you.

**Comment by elmurci** [comment]
@davidkralprofinit just to clarify, are you expecting to make a `getTransactions` call on the deleted account and return a list of transactions?

**Comment by davidkralprofinit** [comment]
Hello, no I am calling getTransactions on the account where the rest balance of deleted account was sent. Thanks

**Comment by elmurci** [comment]
@davidkralprofinit I tried to recreate your issue but seeing the `AccountDelete` transaction. Could you share your code? Interested in your `minLedgerVersion` and `maxLedgerVersion` parameters.

```
[
  {
    type: 'accountDelete',
    address: 'r9gHv9M6onooNre8w8DWEfAhhMzARs8wuQ',
    sequence: 62112763,
    id: '6FF03FF338964206E1610A3411F06CCFD119BD9031C2B6CE2E46E053B4015891',
    specification: {
      destination: 'rPLCnDVaSmUQhg5Hz9ZsMvyA4ioC2qpiwz',
      destinationTag: 2035397819,
      destinationXAddress: 'XV5LmqaAvp4My9eDJcZZn9MQ1RpmKCPERTVhGZYhSL4C7t4'
    },
    outcome: {
      result: 'tesSUCCESS',
      timestamp: '2021-03-10T14:57:31.000Z',
      fee: '5',
      balanceChanges: [Object],
      orderbookChanges: {},
      ledgerVersion: 62113078,
      indexInLedger: 18
    }
  },
  {
    type: 'payment',
    address: 'r9gHv9M6onooNre8w8DWEfAhhMzARs8wuQ',
    sequence: 62112762,
    id: '80D9538A3784999C32F6E037329423A69E9AF26BECAD8B61AE41B014F06A6090',
    specification: { source: [Object], destination: [Object] },
    outcome: {
      result: 'tesSUCCESS',
      timestamp: '2021-03-10T14:43:10.000Z',
      fee: '0.005',
      balanceChanges: [Object],
      orderbookChanges: {},
      ledgerVersion: 62112855,
      indexInLedger: 46,
      deliveredAmount: [Object]
    }
  },
  ...
]

**Comment by davidkralprofinit** [comment]
Thanks for the example, I already see it. We are checking if deliveredAmount is present and filtering out transactions when not. The issue is on our side then. But can I ask, is there a reason why the account deletion transaction type does not have the deliveredAmount?

Thanks

**Comment by gnurag** [comment]
> Thanks for the example, I already see it. We are checking if deliveredAmount is present and filtering out transactions when not. The issue is on our side then. But can I ask, is there a reason why the account deletion transaction type does not have the deliveredAmount?
> 
> Thanks

This may be related to https://github.com/ripple/rippled/issues/3431 and https://github.com/ripple/rippled/issues/3394

**Comment by q411** [comment]
https://github.com/ripple/ripple-lib/issues/1380

**Comment by mDuo13** [comment]
The documentation is correct, so closing this issue.
